const cards = [
	{ x: "浴びます", y: "あびます", z: "Mandi" },
	{ x: "危ない", y: "あぶない", z: "Bahaya" },
	{ x: "油", y: "あぶら", z: "Minyak" },
	{ x: "間", y: "あいだ", z: "Diantara" },
	{ x: "会います", y: "あいます", z: "Bertemu" },
	{ x: "味", y: "あじ", z: "Rasa" },
	{ x: "赤い", y: "あかい", z: "Merah" },
	{ x: "明るい", y: "あかるい", z: "Terang, cerah" },
	{ x: "開けます", y: "あけます", z: "Membuka" },
	{ x: "秋", y: "あき", z: "Musim gugur" },
	{ x: "開きます", y: "あきます", z: "Terbuka" },
	{ x: "甘い", y: "あまい", z: "Manis" },
	{ x: "雨", y: "あめ", z: "Hujan" },
	{ x: "姉", y: "あね", z: "Kaka cewe(saya)" },
	{ x: "兄", y: "あに", z: "Kaka cowo(saya)" },
	{ x: "案内します", y: "あんないします", z: "Memandu" },
	{ x: "安心します", y: "あんしんします", z: "Lega" },
	{ x: "暗証番号", y: "あんしょうばんごう", z: "Nomor PIN" },
	{ x: "安全", y: "あんぜん", z: "Aman" },
	{ x: "青い", y: "あおい", z: "Biru" },
	{ x: "洗います", y: "あらいます", z: "Mencuci" },
	{ x: "朝", y: "あさ", z: "Pagi" },
	{ x: "朝ご飯", y: "あさごはん", z: "Makan pagi" },
	{ x: "足", y: "あし", z: "Kaki" },
	{ x: "明日", y: "あした", z: "Besok" },
	{ x: "遊びます", y: "あそびます", z: "Bermain" },
	{ x: "頭", y: "あたま", z: "Kepala" },
	{ x: "新しい", y: "あたらしい", z: "Baru" },
	{ x: "暖かい", y: "あたたかい", z: "Hangat" },
	{ x: "後で", y: "あとで", z: "Setelah" },
	{ x: "暑い", y: "あつい", z: "Panas (cuaca)" },
	{ x: "厚い", y: "あつい", z: "Tebal" },
	{ x: "熱い", y: "あつい", z: "Panas (benda)" },
	{ x: "集めます", y: "あつめます", z: "Mengumpulkan" },
	{ x: "場合", y: "ばあい", z: "Apabila" },
	{ x: "晩ご飯", y: "ばんごはん", z: "Makan malam" },
	{ x: "勉強します", y: "べんきょうします", z: "Belajar" },
	{ x: "便利", y: "べんり", z: "Praktis" },
	{ x: "弁当", y: "べんとう", z: "Nasi bekal" },
	{ x: "僕", y: "ぼく", z: "Aku" },
	{ x: "忘年会", y: "ぼうねんかい", z: "Pesta akhir tahun" },
	{ x: "部長", y: "ぶちょう", z: "Manager" },
	{ x: "部品", y: "ぶひん", z: "Porsi (mesin)" },
	{ x: "文学", y: "ぶんがく", z: "Sastra" },
	{ x: "文化", y: "ぶんか", z: "Budaya" },
	{ x: "豚肉", y: "ぶたにく", z: "Daging babi" },
	{ x: "病院", y: "びょういん", z: "Rumah sakit" },
	{ x: "病気", y: "びょうき", z: "Sakit" },
	{ x: "血", y: "ち", z: "Darah" },
	{ x: "父", y: "ちち", z: "Ayah" },
	{ x: "小さい", y: "ちいさい", z: "Kecil" },
	{ x: "近い", y: "ちかい", z: "Dekat" },
	{ x: "近く", y: "ちかく", z: "Di dekat" },
	{ x: "地下鉄", y: "ちかてつ", z: "Kereta bawah tanah" },
	{ x: "遅刻します", y: "ちこくします", z: "Terlambat" },
	{ x: "地図", y: "ちず", z: "Peta" },
	{ x: "調子", y: "ちょうし", z: "Keadaan" },
	{ x: "中学校", y: "ちゅうがっこう", z: "SMP" },
	{ x: "中学生", y: "ちゅうがくせい", z: "Siswa SMP" },
	{ x: "中国", y: "ちゅうごく", z: "China" },
	{ x: "注文します", y: "ちゅうもんします", z: "Memesan" },
	{ x: "台所", y: "だいどころ", z: "Dapur" },
	{ x: "大学", y: "だいがく", z: "Universitas" },
	{ x: "大学院", y: "だいがくいん", z: "Pendidikan S2" },
	{ x: "大学生", y: "だいがくせい", z: "Mahasiswa" },
	{ x: "大丈夫", y: "だいじょうぶ", z: "Tidak apa-apa" },
	{ x: "出します", y: "だします", z: "Mengeluarkan, mengirim" },
	{ x: "出会い", y: "であい", z: "Pertemuan" },
	{ x: "出口", y: "でぐち", z: "Pintu keluar" },
	{ x: "出かけます", y: "でかけます", z: "Pergi keluar" },
	{ x: "出ます", y: "でます", z: "Keluar" },
	{ x: "電池", y: "でんち", z: "Baterai" },
	{ x: "電源", y: "でんげん", z: "Power supply" },
	{ x: "電源を入れます", y: "でんげんをいれます", z: "Menyalakan power" },
	{ x: "電源を切ります", y: "でんげんをきります", z: "Mematikan power" },
	{ x: "電気", y: "でんき", z: "Listrik" },
	{ x: "電気代", y: "でんきだい", z: "Biaya listrik" },
	{ x: "電波", y: "でんぱ", z: "Sinyal" },
	{ x: "電車", y: "でんしゃ", z: "Kereta" },
	{ x: "電子辞書", y: "でんしじしょ", z: "Kamus digital" },
	{ x: "電子レンジ", y: "でんしレンジ", z: "Microwave" },
	{ x: "電話", y: "でんわ", z: "Telepon" },
	{ x: "電話代", y: "でんわだい", z: "Biaya telepon" },
	{ x: "電話します", y: "でんわします", z: "Menelpon" },
	{ x: "度", y: "ど", z: "Derajat, suhu" },
	{ x: "動物園", y: "どうぶつえん", z: "Kebun Binatang" },
	{ x: "動画", y: "どうが", z: "Video" },
	{ x: "道具", y: "どうぐ", z: "Peralatan" },
	{ x: "絵", y: "え", z: "Gambar, lukisan" },
	{ x: "映画", y: "えいが", z: "Film" },
	{ x: "映画館", y: "えいがかん", z: "Gedung bioskop" },
	{ x: "英語", y: "えいご", z: "Bahasa Inggris" },
	{ x: "駅", y: "えき", z: "Stasiun" },
	{ x: "円", y: "えん", z: "Yen" },
	{ x: "選びます", y: "えらびます", z: "Memilih" },
	{ x: "不安", y: "ふあん", z: "Gelisah" },
	{ x: "不便", y: "ふべん", z: "Tidak praktis" },
	{ x: "不合格します", y: "ふごうかくします", z: "Tidak lulus ujian" },
	{ x: "深い", y: "ふかい", z: "Dalam" },
	{ x: "服", y: "ふく", z: "Baju" },
	{ x: "分", y: "ふん", z: "Menit" },
	{ x: "降ります", y: "ふります", z: "Turun" },
	{ x: "風呂場", y: "ふろば", z: "Kamar mandi" },
	{ x: "古い", y: "ふるい", z: "Lama, lawas" },
	{ x: "二人", y: "ふたり", z: "Dua orang" },
	{ x: "二つ", y: "ふたつ", z: "Dua barang" },
	{ x: "太い", y: "ふとい", z: "Gemuk" },
	{ x: "二日", y: "ふつか", z: "Tanggal 2" },
	{ x: "冬", y: "ふゆ", z: "Musim dingin" },
	{ x: "冬休み", y: "ふゆやすみ", z: "Liburan musim dingin" },
	{ x: "不在", y: "ふざい", z: "Absen" },
	{ x: "外国人", y: "がいこくじん", z: "Orang asing" },
	{ x: "外出", y: "がいしゅつ", z: "Berada di luar kantor" },
	{ x: "学校", y: "がっこう", z: "Sekolah" },
	{ x: "学生", y: "がくせい", z: "Siswa, pelajar" },
	{ x: "頑張ります", y: "がんばります", z: "Bersempangat" },
	{ x: "現場", y: "げんば", z: "Tempat kerja lapangan" },
	{ x: "原因", y: "げんいん", z: "Penyebab" },
	{ x: "元気", y: "げんき", z: "Sehat" },
	{ x: "現金", y: "げんきん", z: "Uang tunai" },
	{ x: "月曜日", y: "げつようび", z: "Hari Senin" },
	{ x: "銀行", y: "ぎんこう", z: "Bank" },
	{ x: "銀行員", y: "ぎんこういん", z: "Pegawai bank" },
	{ x: "五", y: "ご", z: "Lima" },
	{ x: "午後", y: "ごご", z: "Siang, sore, PM" },
	{ x: "ごみ箱", y: "ごみばこ", z: "Tempat sampah" },
	{ x: "ご主人", y: "ごしゅじん", z: "Suami orang lain" },
	{ x: "合格します", y: "ごうかくします", z: "Lulus ujian" },
	{ x: "午前", y: "ごぜん", z: "Pagi AM" },
	{ x: "牛肉", y: "ぎゅうにく", z: "Daging sapi" },
	{ x: "牛乳", y: "ぎゅうにゅう", z: "Susu sapi" },
	{ x: "歯", y: "は", z: "Gigi" },
	{ x: "葉", y: "は", z: "Daun" },
	{ x: "八", y: "はち", z: "Delapan" },
	{ x: "母", y: "はは", z: "Ibu(saya)" },
	{ x: "母の日", y: "ははのひ", z: "Hari Ibu" },
	{ x: "入ります", y: "はいります", z: "Masuk" },
	{ x: "初めて", y: "はじめて", z: "Pertama kalinya" },
	{ x: "始まります", y: "はじまります", z: "Mulai" },
	{ x: "始めます", y: "はじめます", z: "Memulai" },
	{ x: "運びます", y: "はこびます", z: "Mengangkut" },
	{ x: "半", y: "はん", z: "Setengah" },
	{ x: "花", y: "はな", z: "Bunga" },
	{ x: "花見", y: "はなみ", z: "Piknik melihat bunga" },
	{ x: "花屋", y: "はなや", z: "Toko bunga" },
	{ x: "反対します", y: "はんたいします", z: "Menentang, berlawanan" },
	{ x: "払います", y: "はらいます", z: "Membayar" },
	{ x: "春", y: "はる", z: "Musim semi" },
	{ x: "走ります", y: "はしります", z: "Berlari" },
	{ x: "働きます", y: "はたらきます", z: "Bekerja" },
	{ x: "二十日", y: "はつか", z: "Tanggal 20" },
	{ x: "速い", y: "はやい", z: "Cepat (benda bergerak)" },
	{ x: "早い", y: "はやい", z: "Cepat (lebih awal)" },
	{ x: "外します", y: "はずします", z: "Melepaskan" },
	{ x: "返事", y: "へんじ", z: "Balasan" },
	{ x: "下手", y: "へた", z: "Tidak ahli" },
	{ x: "部屋", y: "へや", z: "Kamar" },
	{ x: "日", y: "ひ", z: "Matahari" },
	{ x: "火", y: "ひ", z: "Api" },
	{ x: "日々", y: "ひび", z: "Hari-hari" },
	{ x: "左", y: "ひだり", z: "Kiri" },
	{ x: "東", y: "ひがし", z: "Timur" },
	{ x: "引き出し", y: "ひきだし", z: "Laci" },
	{ x: "引きます", y: "ひきます", z: "Memainkan alat musik" },
	{ x: "弾きます", y: "ひきます", z: "Menarik" },
	{ x: "飛行機", y: "ひこうき", z: "Pesawat" },
	{ x: "低い", y: "ひくい", z: "Rendah" },
	{ x: "暇", y: "ひま", z: "Senggang" },
	{ x: "広い", y: "ひろい", z: "Luas" },
	{ x: "昼", y: "ひる", z: "Siang" },
	{ x: "昼ご飯", y: "ひるごはん", z: "Makan siang" },
	{ x: "一人", y: "ひとり", z: "Satu orang" },
	{ x: "一人で", y: "ひとりで", z: "Sendirian" },
	{ x: "一つ", y: "ひとつ", z: "Satu buah" },
	{ x: "必要", y: "ひつよう", z: "Diperlukan" },
	{ x: "冷やします", y: "ひやします", z: "Mendinginkan" },
	{ x: "北海道", y: "ほっかいどう", z: "Hokkaido" },
	{ x: "本", y: "ほん", z: "Buku" },
	{ x: "本社", y: "ほんしゃ", z: "Kantor pusat" },
	{ x: "本屋", y: "ほんや", z: "Toko buku" },
	{ x: "本当", y: "ほんとう", z: "Yang sebenarnya" },
	{ x: "訪問します", y: "ほうもんします", z: "Mengunjungi" },
	{ x: "百", y: "ひゃく", z: "Ratus" },
	{ x: "一", y: "いち", z: "Satu" },
	{ x: "一度", y: "いちど", z: "Satu kali" },
	{ x: "一月", y: "いちがつ", z: "Januari" },
	{ x: "一年中", y: "いちねんじゅう", z: "Satu tahun penuh" },
	{ x: "イギリス人", y: "いぎりすじん", z: "Orang Inggris" },
	{ x: "良い", y: "いい", z: "Bagus" },
	{ x: "生け花", y: "いけばな", z: "Seni merangkai bunga" },
	{ x: "意見", y: "いけん", z: "Pendapat" },
	{ x: "行きます", y: "いきます", z: "Pergi" },
	{ x: "一か月", y: "いっかげつ", z: "Selama 1 bulan" },
	{ x: "今", y: "いま", z: "Sekarang" },
	{ x: "居間", y: "いま", z: "Ruang keluarga" },
	{ x: "意味", y: "いみ", z: "Arti" },
	{ x: "妹", y: "いもうと", z: "Adik perempuan" },
	{ x: "妹さん", y: "いもうとさん", z: "Adik perempuan/org lain" },
	{ x: "田舎", y: "いなか", z: "Desa, kampung" },
	{ x: "犬", y: "いぬ", z: "Anjing" },
	{ x: "入れます", y: "いれます", z: "Memasukkan" },
	{ x: "入口", y: "いりぐち", z: "Pintu masuk" },
	{ x: "要ります", y: "いります", z: "Memerlukan" },
	{ x: "色々", y: "いろいろ", z: "Bermacam-macam" },
	{ x: "医者", y: "いしゃ", z: "Dokter" },
	{ x: "忙しい", y: "いそがしい", z: "Sibuk" },
	{ x: "急ぎます", y: "いそぎます", z: "Bergegas" },
	{ x: "一週間", y: "いしゅうかん", z: "Selama 1 minggu" },
	{ x: "痛い", y: "いたい", z: "Sakit" },
	{ x: "五日", y: "いつか", z: "Tanggal 5" },
	{ x: "祝い", y: "いわい", z: "Perayaan" },
	{ x: "祝います", y: "いわいます", z: "Merayakan" },
	{ x: "時", y: "じ", z: "Satuan jam" },
	{ x: "自分", y: "じぶん", z: "Diri sendiri" },
	{ x: "自分で", y: "じぶんで", z: "Oleh diri sendiri" },
	{ x: "自動車", y: "じどうしゃ", z: "Mobil" },
	{ x: "時間", y: "じかん", z: "Waktu" },
	{ x: "事故", y: "じこ", z: "Kecelakaan" },
	{ x: "神社", y: "じんじゃ", z: "Kuil" },
	{ x: "自信", y: "じしん", z: "Percaya diri" },
	{ x: "自転車", y: "じてんしゃ", z: "Sepeda" },
	{ x: "上手", y: "じょうず", z: "Pintar (skill)" },
	{ x: "授業", y: "じゅぎょう", z: "Pelajaran" },
	{ x: "受験票", y: "じゅけんひょう", z: "Kartu ujian" },
	{ x: "受験料", y: "じゅけんりょう", z: "Biaya ujian" },
	{ x: "十", y: "じゅう", z: "10" },
	{ x: "十一日", y: "じゅういちにち", z: "Tanggal 11" },
	{ x: "住所", y: "じゅうしょ", z: "Alamat rumah" },
	{ x: "十四日", y: "じゅうよっか", z: "Tanggal 14" },
	{ x: "換えます", y: "かえます", z: "Menukar" },
	{ x: "変えます", y: "かえます", z: "Mengganti" },
	{ x: "帰ります", y: "かえります", z: "Pulang" },
	{ x: "返します", y: "かえします", z: "Mengembalikan" },
	{ x: "家具", y: "かぐ", z: "Furniture" },
	{ x: "～回", y: "～かい", z: "-kali" },
	{ x: "海外", y: "かいがい", z: "Luar negeri" },
	{ x: "買い物します", y: "かいものします", z: "Berbelanja" },
	{ x: "会話", y: "かいわ", z: "Percakapan" },
	{ x: "火事", y: "かじ", z: "Kebakaran" },
	{ x: "書きます", y: "かきます", z: "Menulis" },
	{ x: "描きます", y: "かきます", z: "Menggambar" },
	{ x: "確認します", y: "かくにんします", z: "Memastikan" },
	{ x: "紙", y: "かみ", z: "Kertas" },
	{ x: "考えます", y: "かんがえます", z: "Berfikir" },
	{ x: "漢字", y: "かんじ", z: "Huruf kanji" },
	{ x: "韓国", y: "かんこく", z: "Korea" },
	{ x: "観光地", y: "かんこち", z: "Tempat wisata" },
	{ x: "簡単", y: "かんたん", z: "Mudah" },
	{ x: "顔", y: "かお", z: "Wajah" },
	{ x: "体", y: "からだ", z: "Badan" },
	{ x: "辛い", y: "からい", z: "Pedas" },
	{ x: "借ります", y: "かります", z: "Meminjam" },
	{ x: "軽い", y: "かるい", z: "Ringan" },
	{ x: "傘", y: "かさ", z: "Payung" },
	{ x: "貸します", y: "かします", z: "Meminjamkan" },
	{ x: "肩", y: "かた", z: "Bahu" },
	{ x: "片つけます", y: "かたつけます", z: "Membereskan" },
	{ x: "川", y: "かわ", z: "Sungai" },
	{ x: "火曜日", y: "かようび", z: "Hari Selasa" },
	{ x: "風", y: "かぜ", z: "Angin" },
	{ x: "風邪", y: "かぜ", z: "Flu/masuk angin" },
	{ x: "家族", y: "かぞく", z: "Keluarga" },
	{ x: "結果", y: "けっか", z: "Hasil" },
	{ x: "結婚式", y: "けっこんしき", z: "Upacara pernikahan" },
	{ x: "結婚します", y: "けっこんします", z: "Menikah" },
	{ x: "見学します", y: "けんがくします", z: "Melakukan observasi" },
	{ x: "今朝", y: "けさ", z: "Tadi pagi" },
	{ x: "消します", y: "けします", z: "Mematikan, menghapus" },
	{ x: "木", y: "き", z: "Pohon" },
	{ x: "気分", y: "きぶん", z: "Perasaan (mood)" },
	{ x: "消えます", y: "きえます", z: "Padam, mati" },
	{ x: "聞きます", y: "ききます", z: "Mendengarkan" },
	{ x: "聞こえます", y: "きこえます", z: "Terdengar" },
	{ x: "来ます", y: "きます", z: "Datang" },
	{ x: "決めます", y: "きめます", z: "Memutuskan" },
	{ x: "君", y: "きみ", z: "Kamu" },
	{ x: "気持ち", y: "きもち", z: "Perasaan" },
	{ x: "着物", y: "きもの", z: "Kimono" },
	{ x: "金額", y: "きんがく", z: "Jumlah uang" },
	{ x: "昨日", y: "きのう", z: "Kemarin" },
	{ x: "金曜日", y: "きんようび", z: "Hari Jumat" },
	{ x: "記入します", y: "きにゅうします", z: "Mengisi formular" },
	{ x: "切符", y: "きっぷ", z: "Karcis, tiket" },
	{ x: "嫌い", y: "きらい", z: "Benci" },
	{ x: "切れます", y: "きれます", z: "Putus" },
	{ x: "切ります", y: "きります", z: "Memotong" },
	{ x: "規則", y: "きそく", z: "Peraturan" },
	{ x: "喫茶店", y: "きっさてん", z: "Kafe" },
	{ x: "北", y: "きた", z: "Utara" },
	{ x: "子供の日", y: "こどものひ", z: "Hari anak" },
	{ x: "声", y: "こえ", z: "Suara" },
	{ x: "九日", y: "ここのか", z: "Tanggal 9" },
	{ x: "心", y: "こころ", z: "Hati" },
	{ x: "細かいお金", y: "こまかいおかね", z: "Uang receh" },
	{ x: "今晩", y: "こんばん", z: "Malam ini" },
	{ x: "今度", y: "こんど", z: "Waktu berikutnya" },
	{ x: "今月", y: "こんげつ", z: "Bulan ini" },
	{ x: "今週", y: "こんしゅう", z: "Minggu ini" },
	{ x: "コピー機", y: "コピーき", z: "Mesin fotokopi" },
	{ x: "答え", y: "こたえ", z: "Jawaban" },
	{ x: "答えます", y: "こたえます", z: "Menjawab" },
	{ x: "言葉", y: "ことば", z: "Kosakata" },
	{ x: "今年", y: "ことし", z: "Tahun ini" },
	{ x: "公園", y: "こうえん", z: "Taman" },
	{ x: "工事", y: "こうじ", z: "Kerja kontruksi" },
	{ x: "工場", y: "こうじょう", z: "Pabrik" },
	{ x: "高校", y: "こうこう", z: "SMA" },
	{ x: "高校生", y: "こうこうせい", z: "Siswa SMA" },
	{ x: "交通", y: "こうつう", z: "Lalu lintas" },
	{ x: "口座", y: "こうざ", z: "Rekening bank" },
	{ x: "口座番号", y: "こうざばんごう", z: "Nomor rekening bank" },
	{ x: "九", y: "く", z: "Sembilan" },
	{ x: "首を切ります", y: "くびをきります", z: "Memecat" },
	{ x: "口", y: "くち", z: "Mulut" },
	{ x: "果物", y: "くだもの", z: "Buah-buahan" },
	{ x: "九月", y: "くがつ", z: "Bulan 9" },
	{ x: "曇", y: "くも", z: "Mendung" },
	{ x: "暗い", y: "くらい", z: "Gelap" },
	{ x: "黒い", y: "くろい", z: "Hitam" },
	{ x: "苦しい", y: "くるしい", z: "Menderita" },
	{ x: "薬", y: "くすり", z: "Obat" },
	{ x: "薬屋", y: "くすりや", z: "Toko obat" },
	{ x: "空気", y: "くうき", z: "Udara" },
	{ x: "詳しい", y: "くわしい", z: "Teliti" },
	{ x: "許可", y: "きょか", z: "Ijin" },
	{ x: "去年", y: "きょねん", z: "Tahun lalu" },
	{ x: "今日", y: "きょう", z: "Hari ini" },
	{ x: "兄弟", y: "きょうだい", z: "Saudara kandung" },
	{ x: "教室", y: "きょうしつ", z: "Ruang kelas" },
	{ x: "京都", y: "きょうと", z: "Kyoto" },
	{ x: "九", y: "きゅう", z: "Sembilan" },
	{ x: "救急車", y: "きゅうきゅうしゃ", z: "Mobil ambulan" },
	{ x: "急に", y: "きゅうに", z: "Tiba-tiba" },
	{ x: "町田", y: "まち", z: "Kota" },
	{ x: "窓", y: "まど", z: "Jendela" },
	{ x: "前", y: "まえ", z: "Depan" },
	{ x: "毎朝", y: "まいあさ", z: "Setiap pagi" },
	{ x: "毎晩", y: "まいばん", z: "Setiap malam" },
	{ x: "毎日", y: "まいにち", z: "Setiap hari" },
	{ x: "毎月", y: "まいつき", z: "Setiap bulan" },
	{ x: "守ります", y: "まもります", z: "Melindungi" },
	{ x: "万", y: "まん", z: "Puluhan ribu" },
	{ x: "間に合います", y: "まにあいます", z: "Tepat waktu" },
	{ x: "祭り", y: "まつり", z: "Festival budaya Jepang" },
	{ x: "回します", y: "まわします", z: "Memutar" },
	{ x: "目", y: "め", z: "Mata" },
	{ x: "目薬", y: "めぐすり", z: "Obat mata" },
	{ x: "身分証明書", y: "みぶんしょうめいしょ", z: "Kartu identitas diri" },
	{ x: "道", y: "みち", z: "Jalan" },
	{ x: "見えます", y: "みえます", z: "Terlihat" },
	{ x: "右", y: "みぎ", z: "Kanan" },
	{ x: "短い", y: "みじかい", z: "Pendek" },
	{ x: "三日", y: "みっか", z: "Tanggal 3" },
	{ x: "診ます", y: "みます", z: "Memeriksa kesehatan" },
	{ x: "見ます", y: "みます", z: "Melihat, menonton" },
	{ x: "耳", y: "みみ", z: "Telinga" },
	{ x: "南", y: "みなみ", z: "Selatan" },
	{ x: "港", y: "みなと", z: "Pelabuhan" },
	{ x: "店", y: "みせ", z: "Toko" },
	{ x: "見せます", y: "みせます", z: "Memperlihatkan" },
	{ x: "見つけます", y: "みつけます", z: "Menemukan" },
	{ x: "水", y: "みず", z: "Air" },
	{ x: "戻ります", y: "もどります", z: "Kembali" },
	{ x: "戻します", y: "もどします", z: "Mengembalikan" },
	{ x: "木曜日", y: "もくようび", z: "Kamis" },
	{ x: "問題", y: "もんだい", z: "Soal, masalah" },
	{ x: "森", y: "もり", z: "Hutan" },
	{ x: "申し込み", y: "もしこみ", z: "Pendaftaran" },
	{ x: "申し込みます", y: "もしこみます", z: "Mendaftar" },
	{ x: "六日", y: "むいか", z: "Tanggal 6" },
	{ x: "迎えます", y: "むかえます", z: "Menjemput" },
	{ x: "無料", y: "むしょう", z: "Gratis" },
	{ x: "難しい", y: "むずかしい", z: "Sulit, susah" },
	{ x: "長い", y: "ながい", z: "Panjang" },
	{ x: "中", y: "なか", z: "Dalam" },
	{ x: "泣きます", y: "なきます", z: "Menangis" },
	{ x: "亡くなります", y: "なくなります", z: "Meninggal" },
	{ x: "生", y: "なま", z: "Mentah" },
	{ x: "名前", y: "なまえ", z: "Nama" },
	{ x: "波", y: "なみ", z: "Ombak" },
	{ x: "涙", y: "なみだ", z: "Air mata" },
	{ x: "七", y: "なな", z: "Tujuh" },
	{ x: "何月", y: "なんがつ", z: "Bulan berapa" },
	{ x: "何枚", y: "なんまい", z: "Berapa lembar" },
	{ x: "何日", y: "なんにち", z: "Tanggal berapa" },
	{ x: "何人", y: "なんにん", z: "Berapa orang" },
	{ x: "七日", y: "なのか", z: "Tanggal 7" },
	{ x: "治ります", y: "なおります", z: "Sembuh" },
	{ x: "直ります", y: "なおります", z: "Membaik (dari kerusakan)" },
	{ x: "治します", y: "なおします", z: "Membetulkan" },
	{ x: "直します", y: "なおします", z: "Menyembuhkan" },
	{ x: "習います", y: "ならいます", z: "Mempelajari" },
	{ x: "夏", y: "なつ", z: "Musim panas" },
	{ x: "夏休み", y: "なつやすみ", z: "Libur musim panas" },
	{ x: "願います", y: "ねがいます", z: "Memohon" },
	{ x: "猫", y: "ねこ", z: "Kucing" },
	{ x: "寝ます", y: "ねます", z: "Tidur" },
	{ x: "眠い", y: "ねむい", z: "Mengantuk" },
	{ x: "年", y: "ねん", z: "Tahun" },
	{ x: "~年生", y: "ねんせい", z: "Tingkatan kelas sekolah" },
	{ x: "熱", y: "ねつ", z: "Panas, demam" },
	{ x: "二", y: "に", z: "Dua" },
	{ x: "日曜日", y: "にちようび", z: "Hari minggu" },
	{ x: "苦い", y: "にがい", z: "Pahit" },
	{ x: "苦手", y: "にがて", z: "Tidak bisa, tidak ahli" },
	{ x: "日本語", y: "にほんご", z: "Bahasa Jepang" },
	{ x: "二十一日", y: "にじゅういちにち", z: "Tanggal 21" },
	{ x: "二ヶ月", y: "にかげつ", z: "Selama 2 bulan" },
	{ x: "日記", y: "にっき", z: "Buku harian" },
	{ x: "肉屋", y: "にくや", z: "Toko daging" },
	{ x: "荷物", y: "にもつ", z: "Barang bawaan" },
	{ x: "人間関係", y: "にんげんかんけい", z: "Hubungan antar manusia" },
	{ x: "西", y: "にし", z: "Barat" },
	{ x: "二週間", y: "にしゅうかん", z: "Selama 2 minggu" },
	{ x: "庭", y: "にわ", z: "Halaman rumah" },
	{ x: "登ります", y: "のぼります", z: "Mendaki" },
	{ x: "飲み会", y: "のみかい", z: "Acara minum bersama" },
	{ x: "飲みます", y: "のみます", z: "Minum" },
	{ x: "飲み物", y: "のみもの", z: "Minuman" },
	{ x: "乗ります", y: "のります", z: "Naik kendaraan" },
	{ x: "入学式", y: "にゅうがくしき", z: "Upacara masuk sekolah" },
	{ x: "入学試験", y: "にゅうがくしけん", z: "Ujian masuk sekolah" },
	{ x: "入院します", y: "にゅういんします", z: "Masuk rumah sakit, opname" },
	{ x: "覚えます", y: "おぼえます", z: "Mengingat, menghafal" },
	{ x: "お茶", y: "おちゃ", z: "Teh Jepang" },
	{ x: "落ちます", y: "おちます", z: "Jatuh" },
	{ x: "お風呂", y: "おふろ", z: "Bak mandi" },
	{ x: "お祈りします", y: "おいのりします", z: "Berdoa" },
	{ x: "お祝い", y: "おいわい", z: "Perayaan" },
	{ x: "お祝いします", y: "おいわいします", z: "Merayakan" },
	{ x: "お母さん", y: "おかあさん", z: "Ibu orang lain" },
	{ x: "起きます", y: "おきます", z: "Bangun" },
	{ x: "起きます", y: "おきます", z: "Terjadi" },
	{ x: "行います", y: "おこないます", z: "Menyelenggarakan" },
	{ x: "怒ります", y: "おこります", z: "Marah" },
	{ x: "おこします", y: "おこします", z: "Membangunkan" },
	{ x: "遅れます", y: "おくれます", z: "Terlambat" },
	{ x: "送ります", y: "おくります", z: "Mengirim" },
	{ x: "贈り物", y: "おくりもの", z: "Bingkisan" },
	{ x: "奥さん", y: "おくさん", z: "Istri orang lain" },
	{ x: "お客さん", y: "おきゃくさん", z: "Tamu" },
	{ x: "お祭り", y: "おまつり", z: "Festival budaya" },
	{ x: "お土産", y: "おみやげ", z: "Oleh-oleh" },
	{ x: "思い", y: "おもい", z: "Berat" },
	{ x: "思い出します", y: "おもいだします", z: "Kenangan" },
	{ x: "面白い", y: "おもしろい", z: "Menarik, seru" },
	{ x: "お姉さん", y: "おねえさん", z: "Kakak perempuan orang lain" },
	{ x: "音楽", y: "おんがく", z: "Musik" },
	{ x: "お兄さん", y: "おにいさん", z: "Kakak laki-laki orang lain" },
	{ x: "多い", y: "おおい", z: "Banyak" },
	{ x: "大きい", y: "おおきい", z: "Besar" },
	{ x: "おれます", y: "おれます", z: "Patah" },
	{ x: "折り紙", y: "おりがみ", z: "Seni lipat kertas" },
	{ x: "降ります", y: "おります", z: "Turun" },
	{ x: "下ろします", y: "おろします", z: "Menurunkan barang" },
	{ x: "下ろします", y: "おろします", z: "Mengambil uang" },
	{ x: "お酒", y: "おさけ", z: "Sake" },
	{ x: "お皿", y: "おさら", z: "Piring" },
	{ x: "教えます", y: "おしえます", z: "Mengajari, memberitahu" },
	{ x: "押入れ", y: "おしいれ", z: "Lemari dinding" },
	{ x: "押します", y: "おします", z: "Menekan, mendorong" },
	{ x: "お知らせ", y: "おしらせ", z: "Pengumuman" },
	{ x: "お正月", y: "おしょうがつ", z: "Tahun baru" },
	{ x: "遅い", y: "おそい", z: "Lama, lambat" },
	{ x: "お手洗い", y: "おてあらい", z: "Toilet" },
	{ x: "お寺", y: "おてら", z: "Kuil Buddha" },
	{ x: "音", y: "おと", z: "Bunyi" },
	{ x: "お父さん", y: "おとうさん", z: "Ayah orang lain" },
	{ x: "弟", y: "おとうと", z: "Adik laki-laki saya" },
	{ x: "弟さん", y: "おとうとさん", z: "Adik laki-laki orang lain" },
	{ x: "お釣り", y: "おつり", z: "Uang kembalian" },
	{ x: "夫", y: "おっと", z: "Suami" },
	{ x: "終わり", y: "おわり", z: "Selesai" },
	{ x: "お湯", y: "おゆ", z: "Air panas" },
	{ x: "分", y: "ぷん", z: "Menit" },
	{ x: "来月", y: "らいげつ", z: "Bulan depan" },
	{ x: "来年", y: "らいねん", z: "Tahun depan" },
	{ x: "来週", y: "らいしゅう", z: "Minggu depan" },
	{ x: "楽", y: "らく", z: "Ringan (untuk dilakukan)" },
	{ x: "冷蔵庫", y: "れいぞうこ", z: "Lemari es" },
	{ x: "歴史", y: "れきし", z: "Sejarah" },
	{ x: "連休", y: "れんきゅう", z: "Libur panjang" },
	{ x: "練習", y: "れんしゅう", z: "Latihan" },
	{ x: "利用します", y: "りようします", z: "Memanfaatkan" },
	{ x: "理由", y: "りゆう", z: "Alasan" },
	{ x: "六", y: "ろく", z: "Enam" },
	{ x: "旅館", y: "りょかん", z: "Hotel khas Jepang" },
	{ x: "旅行", y: "りょこう", z: "Traveling" },
	{ x: "旅行します", y: "りょこうします", z: "Melakukan traveling" },
	{ x: "料金", y: "りょうきん", z: "Biaya" },
	{ x: "料理", y: "りょうり", z: "Masakan" },
	{ x: "両親", y: "りょうしん", z: "Kedua orang tua" },
	{ x: "留学生", y: "りゅうがくせい", z: "Pelajar asing" },
	{ x: "留学します", y: "りゅうがくします", z: "Belajar ke luar negeri" },
	{ x: "茶道", y: "さどう", z: "Upacara minum teh" },
	{ x: "下がります", y: "さがります", z: "Turun" },
	{ x: "探します", y: "さがします", z: "Mencari" },
	{ x: "下げます", y: "さげます", z: "Membungkukkan, menundukkan" },
	{ x: "魚", y: "さかな", z: "Ikan" },
	{ x: "酒", y: "さけ", z: "Sake" },
	{ x: "寒い", y: "さむい", z: "Dingin (untuk udara)" },
	{ x: "三", y: "さん", z: "Tiga" },
	{ x: "参加します", y: "さんかします", z: "Berpartisipasi" },
	{ x: "散歩します", y: "さんぽします", z: "Jalan-jalan" },
	{ x: "洗濯物", y: "せんたくもの", z: "Cucian" },
	{ x: "砂糖", y: "さとう", z: "Gula" },
	{ x: "背が高い", y: "せがたかい", z: "Tubuhnya tinggi" },
	{ x: "生活", y: "せいかつ", z: "Kehidupan sehari-hari" },
	{ x: "成功します", y: "せいこうします", z: "Berhasil, sukses" },
	{ x: "世界中", y: "せかいじゅう", z: "Seluruh dunia" },
	{ x: "席を外します", y: "せきをはずします", z: "Meninggalkan tempat" },
	{ x: "狭い", y: "せまい", z: "Sempit" },
	{ x: "千", y: "せん", z: "Ribuan" },
	{ x: "先月", y: "せんげつ", z: "Bulan lalu" },
	{ x: "先週", y: "せんしゅう", z: "Minggu lalu" },
	{ x: "洗濯機", y: "せんたくき", z: "Mesin cuci" },
	{ x: "洗濯します", y: "せんたくします", z: "Mencuci baju" },
	{ x: "説明します", y: "せつめいします", z: "Menjelaskan" },
	{ x: "説明書", y: "せつめいしょ", z: "Lembar instruksi" },
	{ x: "社会", y: "しゃかい", z: "Masyarakat" },
	{ x: "借金", y: "しゃっきん", z: "Uang pinjaman" },
	{ x: "写真", y: "しゃしん", z: "Foto" },
	{ x: "四", y: "し", z: "Empat" },
	{ x: "幸せ", y: "しあわせ", z: "Bahagia" },
	{ x: "七", y: "しち", z: "Tujuh" },
	{ x: "四月", y: "しがつ", z: "Bulan 4" },
	{ x: "仕事", y: "しごと", z: "Pekerjaan" },
	{ x: "試験", y: "しけん", z: "Ujian" },
	{ x: "島", y: "しま", z: "Pulau" },
	{ x: "閉まります", y: "しまります", z: "Tertutup" },
	{ x: "閉めます", y: "しめます", z: "Menutup" },
	{ x: "新聞", y: "しんぶん", z: "Koran" },
	{ x: "死にます", y: "しにます", z: "Mati, tewas" },
	{ x: "信じます", y: "しんじます", z: "Mempercayai" },
	{ x: "新年会", y: "しんねんかい", z: "Pesta awal tahun" },
	{ x: "心配します", y: "しんぱいします", z: "Khawatir" },
	{ x: "親切", y: "しんせつ", z: "Ramah" },
	{ x: "塩", y: "しお", z: "Garam" },
	{ x: "塩辛い", y: "しおからい", z: "Asin" },
	{ x: "失敗します", y: "しっぱいします", z: "Gagal" },
	{ x: "調べます", y: "しらべます", z: "Mencari informasi, memeriksa" },
	{ x: "知り合い", y: "しりあい", z: "Kenalan" },
	{ x: "知ります", y: "しります", z: "Mengetahui, mengenal" },
	{ x: "白い", y: "しろい", z: "Putih" },
	{ x: "下", y: "した", z: "Bawah" },
	{ x: "舌", y: "した", z: "Lidah" },
	{ x: "質問", y: "しつもん", z: "Pertanyaan" },
	{ x: "静か", y: "しずか", z: "Tenang, sepi, pendiam" },
	{ x: "書道", y: "しょどう", z: "Seni kaligrafi kanji" },
	{ x: "職場", y: "しょくば", z: "Tempat kerja" },
	{ x: "食事します", y: "しょくじします", z: "Makan-makan" },
	{ x: "小学校", y: "しょうがっこう", z: "SD" },
	{ x: "小学生", y: "しょうがくせい", z: "Siswa SD" },
	{ x: "紹介します", y: "しょうかいします", z: "Memperkenalkan" },
	{ x: "小説", y: "しょうせつ", z: "Novel" },
	{ x: "招待状", y: "しょうたいじょう", z: "Surat undangan" },
	{ x: "招待します", y: "しょうたいします", z: "Mengundang" },
	{ x: "出張", y: "しゅっちょう", z: "Pergi dinas" },
	{ x: "宿題", y: "しゅくだい", z: "PR" },
	{ x: "出産", y: "しゅっさん", z: "Kelahiran bayi" },
	{ x: "週末", y: "しゅうまつ", z: "Akhir pekan" },
	{ x: "修理します", y: "しゅうりします", z: "Memperbaiki" },
	{ x: "修正します", y: "しゅうせいします", z: "Melakukan revisi" },
	{ x: "空", y: "そら", z: "Langit" },
	{ x: "外", y: "そと", z: "Luar" },
	{ x: "卒業式", y: "そつぎょうしき", z: "Upacara kelulusan" },
	{ x: "卒業します", y: "そつぎょうします", z: "Lulus dari sekolah" },
	{ x: "送別会", y: "そうべつかい", z: "Pesta perpisahan" },
	{ x: "掃除します", y: "そうじします", z: "Bersih-bersih" },
	{ x: "送料", y: "そうりょう", z: "Biaya kirim" },
	{ x: "すべて", y: "すべて", z: "Semuanya" },
	{ x: "過ごします", y: "すごします", z: "Menghabiskan waktu" },
	{ x: "水曜日", y: "すいようび", z: "Hari Rabu" },
	{ x: "好き", y: "すき", z: "Suka" },
	{ x: "少し", y: "すこし", z: "Sedikit" },
	{ x: "少ない", y: "すくない", z: "Sedikit" },
	{ x: "住みます", y: "すむ", z: "Tinggal" },
	{ x: "相撲", y: "すもう", z: "Sumo" },
	{ x: "住む", y: "すむ", z: "Tinggal" },
	{ x: "捨てます", y: "すてます", z: "Membuang" },
	{ x: "数学", y: "すうがく", z: "Matematika" },
	{ x: "座ります", y: "すわります", z: "Duduk" },
	{ x: "涼しい", y: "すずしい", z: "Sejuk" },
	{ x: "食べ物", y: "たべもの", z: "Makanan" },
	{ x: "立ちます", y: "たちます", z: "Berdiri" },
	{ x: "正しい", y: "ただしい", z: "Benar" },
	{ x: "台風", y: "たいふう", z: "Angin topan" },
	{ x: "大変", y: "たいへん", z: "Berat" },
	{ x: "退院します", y: "たいいんします", z: "Keluar dari opname rumah sakit" },
	{ x: "体重", y: "たいじゅう", z: "Berat badan" },
	{ x: "体温", y: "たいおん", z: "Suhu tubuh" },
	{ x: "体温計", y: "たいおんけい", z: "Termometer" },
	{ x: "大使館", y: "たいしかん", z: "Kantor kedutaan" },
	{ x: "高い", y: "たかい", z: "Tinggi, mahal" },
	{ x: "宅配便", y: "たくはいびん", z: "Layanan delivery" },
	{ x: "卵", y: "たまご", z: "Telur" },
	{ x: "玉ねぎ", y: "たまねぎ", z: "Bawang bombay" },
	{ x: "誕生日", y: "たんじょうび", z: "Hari ulang tahun" },
	{ x: "楽しい", y: "たのしい", z: "Menyenangkan" },
	{ x: "担当者", y: "たんとうしゃ", z: "Penanggung jawab" },
	{ x: "足ります", y: "たりまし", z: "Cukup" },
	{ x: "助けます", y: "たすけます", z: "Menolong" },
	{ x: "建てます", y: "たてます", z: "Mendirikan" },
	{ x: "建物", y: "たてもの", z: "Bangunan" },
	{ x: "手", y: "て", z: "Tangan" },
	{ x: "手紙", y: "てがみ", z: "Surat" },
	{ x: "手土産", y: "てみやげ", z: "Oleh-oleh" },
	{ x: "点", y: "てん", z: "Satuan nilai, skor" },
	{ x: "天気", y: "てんき", z: "Cuaca" },
	{ x: "転勤します", y: "てんきんします", z: "Mutasi kerja" },
	{ x: "天気予報", y: "てんきよほう", z: "Perkiraan cuaca" },
	{ x: "手伝います", y: "てつだいます", z: "Membantu" },
	{ x: "飛びます", y: "とびます", z: "Terbang" },
	{ x: "閉じます", y: "とじます", z: "Menutup mata" },
	{ x: "時計", y: "とけい", z: "Jam" },
	{ x: "特別", y: "とくべつ", z: "Spesial, khusus" },
	{ x: "止まります", y: "とまります", z: "Menginap" },
	{ x: "止めます", y: "とめます", z: "Memarkir mobil" },
	{ x: "友達", y: "ともだち", z: "Teman" },
	{ x: "隣", y: "となり", z: "Sebelah" },
	{ x: "遠い", y: "とおい", z: "Jauh" },
	{ x: "十日", y: "とおか", z: "Tanggal 10" },
	{ x: "図書館", y: "としょかん", z: "Perpustakaan" },
	{ x: "到着します", y: "とうちゃくします", z: "Tiba" },
	{ x: "豆腐", y: "とうふ", z: "Tahu" },
	{ x: "東京", y: "とうきょう", z: "Tokyo" },
	{ x: "一日", y: "ついたち", z: "Tanggal 1" },
	{ x: "使い方", y: "つかいかた", z: "Cara menggunakan" },
	{ x: "使います", y: "つかいます", z: "Menggunakan" },
	{ x: "疲れます", y: "つかれます", z: "Lelah" },
	{ x: "月", y: "つき", z: "Bulan (moon)" },
	{ x: "着きます", y: "つきます", z: "Tiba" },
	{ x: "作ります", y: "つくります", z: "Membuat" },
	{ x: "妻", y: "つま", z: "Istri saya" },
	{ x: "冷たい", y: "つめたい", z: "Dingin untuk benda" },
	{ x: "連れて行きます", y: "つれていきます", z: "Mengajak pergi" },
	{ x: "釣り", y: "つり", z: "Memancing" },
	{ x: "伝えます", y: "つたえます", z: "Menyampaikan pesan" },
	{ x: "通話", y: "つうわ", z: "Panggilan telepon" },
	{ x: "強い", y: "つよい", z: "Kuat" },
	{ x: "上", y: "うえ", z: "Atas" },
	{ x: "動きます", y: "うごきます", z: "Bergerak" },
	{ x: "受けます", y: "うけます", z: "Mengikuti ujian" },
	{ x: "海", y: "うみ", z: "Laut" },
	{ x: "運動します", y: "うんどうします", z: "Berolahraga" },
	{ x: "運転します", y: "うんてんします", z: "Menyetir" },
	{ x: "嬉しい", y: "うれしい", z: "Senang" },
	{ x: "売ります", y: "うります", z: "Menjual" },
	{ x: "後ろ", y: "うしろ", z: "Belakang" },
	{ x: "歌", y: "うた", z: "Lagu" },
	{ x: "歌います", y: "うたいます", z: "Bernyanyi" },
	{ x: "若い", y: "わかい", z: "Muda" },
	{ x: "別れます", y: "わかれます", z: "Berpisah" },
	{ x: "笑います", y: "わらいます", z: "Tertawa" },
	{ x: "悪い", y: "わるい", z: "Buruk, jelek" },
	{ x: "分かります", y: "わかります", z: "Mengerti" },
	{ x: "和食", y: "わしょく", z: "Makanan Jepang" },
	{ x: "忘れます", y: "わすれます", z: "Lupa" },
	{ x: "家賃", y: "やちん", z: "Sewa rumah" },
	{ x: "焼けます", y: "やけます", z: "Terbakar" },
	{ x: "焼きます", y: "やきます", z: "Memanggang, membakar" },
	{ x: "約束", y: "やくそく", z: "Janji" },
	{ x: "山", y: "やま", z: "Gunung" },
	{ x: "やめます", y: "やめます", z: "Berhenti" },
	{ x: "八百屋", y: "やおや", z: "Toko sayur" },
	{ x: "野菜", y: "やさい", z: "Sayur" },
	{ x: "易しい", y: "やさしい", z: "Mudah" },
	{ x: "優しい", y: "やさしい", z: "Baik hati" },
	{ x: "安い", y: "やすい", z: "Murah" },
	{ x: "休みます", y: "やすみます", z: "Beristirahat, libur" },
	{ x: "休みの日", y: "やすみのひ", z: "Hari libur" },
	{ x: "四日", y: "よっか", z: "Tanggal 4" },
	{ x: "呼びます", y: "よびます", z: "Memanggil" },
	{ x: "読みます", y: "よみます", z: "Membaca" },
	{ x: "四", y: "よん", z: "Empat" },
	{ x: "夜", y: "よる", z: "Malam" },
	{ x: "予定", y: "よてい", z: "Jadwal, agenda" },
	{ x: "八日", y: "ようか", z: "Tanggal 8" },
	{ x: "洋食", y: "ようしょく", z: "Makanan ala barat" },
	{ x: "弱い", y: "よわい", z: "Lemah" },
	{ x: "予約します", y: "よやくします", z: "Memesan, melakukan reservasi" },
	{ x: "指", y: "ゆび", z: "Jari" },
	{ x: "雪", y: "ゆき", z: "Salju" },
	{ x: "有料", y: "ゆうりょう", z: "Berbayar" },
	{ x: "郵便局", y: "ゆうびんきょく", z: "Kantor pos" },
	{ x: "有名", y: "ゆうめい", z: "Terkenal" }
	
];