const obj = [
	{
		id: "BAB 1",
		content: [
			{x: "私", y: "わたし", z: "Saya"},
			{x: "あなた", y: "あなた", z: "Anda"},
			{x: "あの人", y: "あのひと", z: "Orang itu"},
			{x: "先生", y: "せんせい", z: "Guru"},
			{x: "教師", y: "きょうし", z: "Guru"},
			{x: "学生", y: "がくせい", z: "Pelajar"},
			{x: "会社員", y: "かいしゃいん", z: "Karyawan perusahaan"},
			{x: "社員", y: "しゃいん", z: "Karyawan"},
			{x: "銀行員", y: "ぎんこういん", z: "Pegawai bank"},
			{x: "医者", y: "いしゃ", z: "Dokter"},
			{x: "研究者", y: "けんきゅうしゃ", z: "Peneliti"},
			{x: "大学", y: "だいがく", z: "Universitas"},
			{x: "病院", y: "びょういん", z: "Rumah sakit"},
			{x: "誰", y: "だれ", z: "Siapa"},
			{x: "何歳", y: "なんさい", z: "Umur berapa"},
			{x: "初めまして", y: "はじめまして", z: "Pertama-tama"},
			{x: "失礼します", y: "しつれいします", z: "Permisi"},
			{x: "お名前は", y: "おなまえは", z: "Siapa nama anda"}
		]
	},
	{
		id: "BAB 2",
		content: [
			{x: "これ", y: "これ", z: "Ini"},
			{x: "それ", y: "それ", z: "Itu"},
			{x: "あれ", y: "あれ", z: "Itu (jauh)"},
			{x: "本", y: "ほん", z: "Buku"},
			{x: "辞書", y: "じしょ", z: "Kamus"},
			{x: "新聞", y: "しんぶん", z: "Koran"},
			{x: "ノート", y: "ノート", z: "Note"},
			{x: "手帳", y: "てちょう", z: "Buku catatan"},
			{x: "名刺", y: "めいし", z: "Kartu nama"},
			{x: "カード", y: "カード", z: "Kartu"},
			{x: "鉛筆", y: "えんぴつ", z: "Pensil"},
			{x: "ボールペン", y: "ボールペン", z: "Ballpoint"},
			{x: "シャープペンシル", y: "シャープペンシル", z: "Pensil mekanik"},
			{x: "かぎ", y: "かぎ", z: "Kunci"},
			{x: "時計", y: "とけい", z: "Jam"},
			{x: "傘", y: "かさ", z: "Payung"},
			{x: "かばん", y: "かばん", z: "Tas"},
			{x: "テレビ", y: "テレビ", z: "TV"},
			{x: "ラジオ", y: "ラジオ", z: "Radio"},
			{x: "カメラ", y: "カメラ", z: "Kamera"},
			{x: "コンピューター", y: "コンピューター", z: "Komputer"},
			{x: "車", y: "くるま", z: "Mobil"},
			{x: "机", y: "つくえ", z: "Meja"},
			{x: "いす", y: "いす", z: "Kursi"},
			{x: "チョコレート", y: "チョコレート", z: "Coklat"},
			{x: "コーヒー", y: "コーヒー", z: "Kopi"},
			{x: "お土産", y: "おみやげ", z: "Oleh-oleh"},
			{x: "英語", y: "えいご", z: "Bahasa Inggris"},
			{x: "日本語", y: "にほんご", z: "Bahasa Jepang"},
			{x: "何", y: "なに", z: "Apa"},
			{x: "そう", y: "そう", z: "Begitu"},
			{x: "あのう", y: "あのう", z: "Eee (ungkapan ragu-ragu)"},
			{x: "えっ", y: "えっ", z: "Eh"},
			{x: "どうぞ", y: "どうぞ", z: "Silahkan"},
			{x: "どうもありがとうございました", y: "どうもありがとうございました", z: "Terima kasih banyak"},
			{x: "そうですか", y: "そうですか", z: "Benarkah"},
			{x: "違います", y: "ちがいます", z: "Salah/bukan/tidak"},
			{x: "これからお世話になります", y: "これからおせわになります", z: "Mulai sekarang mohon bantuannya"},
			{x: "こちらこそよろしく", y: "こちらこそよろしく", z: "Ya sama-sama"}
		]
	},
	{
	id: "BAB 3",
		content: [
			{x: "ここ", y: "ここ", z: "Disini"},
			{x: "そこ", y: "そこ", z: "Disitu"},
			{x: "あそこ", y: "あそこ", z: "Disana"},
			{x: "どこ", y: "どこ", z: "Dimana"},
			{x: "こちら", y: "こちら", z: "Di sebelah sini"},
			{x: "そちら", y: "そちら", z: "Di sebelah situ"},
			{x: "あちら", y: "あちら", z: "Di sebelah sana"},
			{x: "どちら", y: "どちら", z: "Di sebelah mana"},
			{x: "教室", y: "きょうしつ", z: "Ruang kelas"},
			{x: "食堂", y: "しょくどう", z: "Kantin"},
			{x: "事務所", y: "じむしょ", z: "Kantor"},
			{x: "会議室", y: "かいぎしつ", z: "Ruang rapat"},
			{x: "受付", y: "うけつけ", z: "Resepsionist"},
			{x: "ロビー", y: "ロビー", z: "Lobi"},
			{x: "部屋", y: "へや", z: "Kamar"},
			{x: "トイレ", y: "トイレ", z: "Toilet"},
			{x: "階段", y: "かいだん", z: "Tangga"},
			{x: "エレベーター", y: "エレベーター", z: "Lift"},
			{x: "エスカレーター", y: "エスカレーター", z: "Ekskalator"},
			{x: "電話", y: "でんわ", z: "Telepon"},
			{x: "お国", y: "おくに", z: "Negara"},
			{x: "会社", y: "かいしゃ", z: "Perusahaan"},
			{x: "家", y: "うち", z: "Rumah"},
			{x: "靴", y: "くつ", z: "Sepatu"},
			{x: "ネクタイ", y: "ネクタイ", z: "Dasi"},
			{x: "ワイン", y: "ワイン", z: "Wain"},
			{x: "売り場", y: "うりば", z: "Tempat penjualan"},
			{x: "地下", y: "ちか", z: "Bawah tanah"},
			{x: "何階", y: "なんがい", z: "Lantai berapa"},
			{x: "いくら", y: "いくら", z: "Berapa"},
			{x: "百", y: "ひゃく", z: "Seratus"},
			{x: "千", y: "せん", z: "Seribu"},
			{x: "万", y: "まん", z: "Sepuluh ribu"},
			{x: "すみません", y: "すみません", z: "Maaf"},
			{x: "どうも", y: "どうも", z: "Terima kasih"},
			{x: "いらっしゃいませ", y: "いらっしゃいませ", z: "Selamat datang"},
			{x: "見せてください", y: "みせてください", z: "Silahkan lihat"},
			{x: "デパート", y: "デパート", z: "Departemen store"},
			{x: "屋上", y: "おくじょう", z: "Atap"},
			{x: "遊園地", y: "ゆうえんち", z: "Tempat hiburan"},
			{x: "レストラン", y: "レストラン", z: "Restoran"},
			{x: "催し物会場", y: "もよおしものかいじょう", z: "Tempat pertunjukan"},
			{x: "時計", y: "とけい", z: "Jam"},
			{x: "眼鏡", y: "めがね", z: "Kacamata"},
			{x: "スポーツ用品", y: "ようひん", z: "Peralatan olahraga"},
			{x: "旅行用品", y: "りょこうようひん", z: "Peralatan wisata"},
			{x: "子供の服", y: "こどものふく", z: "Pakaian anak-anak"},
			{x: "おもちゃ", y: "おもちゃ", z: "Mainan"},
			{x: "文房具", y: "ぶんぼうぐ", z: "Alat tulis"},
			{x: "家具", y: "かぐ", z: "Peralatan rumah tangga"},
			{x: "食器", y: "しょっき", z: "Peralatan makan"},
			{x: "電気製品", y: "でんきせいひん", z: "Barang elektronik"},
			{x: "紳士服", y: "しんしふく", z: "Pakaian pria"},
			{x: "婦人服", y: "ふじんふく", z: "Pakaian wanita"},
			{x: "化粧品", y: "けしょうひん", z: "Kosmetik"},
			{x: "食品", y: "しょくひん", z: "Makanan"},
			{x: "駐車場", y: "ちゅうしゃじょう", z: "Tempat parkir"}
		]
	},
	{
		id: "BAB 4",
		content: [
			{x: "起きます", y: "おきます", z: "Bangun tidur"},
			{x: "寝ます", y: "ねます", z: "Tidur"},
			{x: "働きます", y: "はたらきます", z: "Bekerja"},
			{x: "休みます", y: "やすみます", z: "Libur, istirahat"},
			{x: "勉強します", y: "べんきょうします", z: "Belajar"},
			{x: "終わります", y: "おわります", z: "Selesai"},
			{x: "銀行", y: "ぎんこう", z: "Bank"},
			{x: "郵便局", y: "ゆうびんきょく", z: "Kantor pos"},
			{x: "図書館", y: "としょかん", z: "Perpustakaan"},
			{x: "美術館", y: "びじゅつかん", z: "Gedung kesenian"},
			{x: "今", y: "いま", z: "Sekarang"},
			{x: "半", y: "はん", z: "Setengah"},
			{x: "何時", y: "なんじ", z: "Jam berapa"},
			{x: "何分", y: "なんぷん", z: "Berapa menit"},
			{x: "午前", y: "ごぜん", z: "A.M"},
			{x: "午後", y: "ごご", z: "P.M"},
			{x: "朝", y: "あさ", z: "Pagi"},
			{x: "昼", y: "ひる", z: "Siang"},
			{x: "夜", y: "よる", z: "Malam"},
			{x: "一昨日", y: "おととい", z: "Kemarin lusa"},
			{x: "昨日", y: "きのう", z: "Kemarin"},
			{x: "今日", y: "きょう", z: "Hari ini"},
			{x: "明日", y: "あした", z: "Besok"},
			{x: "明後日", y: "あさって", z: "Besok lusa"},
			{x: "今朝", y: "けさ", z: "Tadi pagi"},
			{x: "今晩", y: "こんばん", z: "Malam ini"},
			{x: "休み", y: "やすみ", z: "Libur"},
			{x: "昼休み", y: "ひるやすみ", z: "Istirahat siang"},
			{x: "試験", y: "しけん", z: "Ujian"},
			{x: "会議", y: "かいぎ", z: "Rapat"},
			{x: "映画", y: "えいが", z: "Film"},
			{x: "毎朝", y: "まいあさ", z: "Setiap pagi"},
			{x: "毎晩", y: "まいばん", z: "Setiap malam"},
			{x: "毎日", y: "まいにち", z: "Setiap hari"},
			{x: "大変ですね", y: "たいへんですね", z: "O, berat ya"},
			{x: "番号", y: "ばんごう", z: "Nomor"},
			{x: "何番", y: "なんばん", z: "Nomor berapa"}
		]
	},
	{
		id: "BAB 5",
		content: [
			{x: "行きます", y: "いきます", z: "Pergi"},
			{x: "来ます", y: "きます", z: "Datang"},
			{x: "帰ります", y: "かえります", z: "Pulang"},
			{x: "学校", y: "がっこう", z: "Sekolah"},
			{x: "スーパー", y: "スーパー", z: "Supermarket"},
			{x: "駅", y: "えき", z: "Stasiun"},
			{x: "飛行機", y: "ひこうき", z: "Pesawat"},
			{x: "船", y: "ふね", z: "Kapal"},
			{x: "電車", y: "でんしゃ", z: "Kereta listrik"},
			{x: "地下鉄", y: "ちかてつ", z: "Kereta bawah tanah"},
			{x: "新幹線", y: "しんかんせん", z: "Kereta super cepat"},
			{x: "バス", y: "バス", z: "Bis"},
			{x: "タクシー", y: "タクシー", z: "Taksi"},
			{x: "自転車", y: "じてんしゃ", z: "Sepeda"},
			{x: "歩いて", y: "あるいて", z: "Jalan kaki"},
			{x: "人", y: "ひと", z: "Orang"},
			{x: "友達", y: "ともだち", z: "Teman"},
			{x: "彼女", y: "かのじょ", z: "Dia perempuan"},
			{x: "家族", y: "かぞく", z: "Keluarga"},
			{x: "一人で", y: "ひとりで", z: "Sendirian"},
			{x: "先週", y: "せんしゅう", z: "Minggu lalu"},
			{x: "今週", y: "こんしゅう", z: "Minggu ini"},
			{x: "来週", y: "らいしゅう", z: "Minggu depan"},
			{x: "先月", y: "せんげつ", z: "Bulan lalu"},
			{x: "今月", y: "こんげつ", z: "Bulan ini"},
			{x: "来月", y: "らいげつ", z: "Bulan depan"},
			{x: "去年", y: "きょねん", z: "Tahun lalu"},
			{x: "今年", y: "ことし", z: "Tahun ini"},
			{x: "来年", y: "らいねん", z: "Tahun depan"},
			{x: "誕生日", y: "たんじょうび", z: "Hari ulang tahun"},
			{x: "そうですね", y: "そうですね", z: "Benarkah"},
			{x: "ありがとうございました", y: "ありがとうございました", z: "Terima kasih"},
			{x: "どういたしまして", y: "どういたしまして", z: "Sama-sama"},
			{x: "次の", y: "つぎの", z: "Selanjutnya"},
			{x: "普通", y: "ふつう", z: "Kereta biasa"},
			{x: "急行", y: "きゅうこう", z: "Kereta ekspres"},
			{x: "特急", y: "とっきゅう", z: "Kereta super ekspres"},
			{x: "元日", y: "がんじつ", z: "Tahun baru"},
			{x: "成人の日", y: "せいじんのひ", z: "Hari perayaan menjadi dewasa"},
			{x: "昭和の日", y: "しょうわのひ", z: "Hari Showa"},
			{x: "子供の日", y: "こどものひ", z: "Hari anak"},
			{x: "文化の日", y: "ぶんかのひ", z: "Hari kebudayaan"}
		]
	},
	{
		id: "BAB 6",
		content: [
			{x: "食べます", y: "たべます", z: "Makan"},
			{x: "飲みます", y: "のみます", z: "Minum"},
			{x: "吸います", y: "すいます", z: "Merokok"},
			{x: "見ます", y: "みます", z: "Melihat"},
			{x: "聞きます", y: "ききます", z: "Mendengar"},
			{x: "読みます", y: "よみます", z: "Membaca"},
			{x: "書きます", y: "かきます", z: "Menulis"},
			{x: "買います", y: "かいます", z: "Membeli"},
			{x: "撮ります", y: "とります", z: "Mengambil"},
			{x: "会います", y: "あいます", z: "Bertemu"},
			{x: "ご飯", y: "ごはん", z: "Nasi"},
			{x: "朝ご飯", y: "あさごはん", z: "Sarapan"},
			{x: "昼ご飯", y: "ひるごはん", z: "Makan siang"},
			{x: "晩ご飯", y: "ばんごはん", z: "Makan malam"},
			{x: "パン", y: "パン", z: "Roti"},
			{x: "たまご", y: "たまご", z: "Telur"},
			{x: "肉", y: "にく", z: "Daging"},
			{x: "魚", y: "さかな", z: "Ikan"},
			{x: "野菜", y: "やさい", z: "Sayuran"},
			{x: "果物", y: "くだもの", z: "Buah-buahan"},
			{x: "水", y: "みず", z: "Air"},
			{x: "お茶", y: "おちゃ", z: "Teh hijau"},
			{x: "紅茶", y: "こうちゃ", z: "Teh"},
			{x: "牛乳", y: "ぎゅうにゅう", z: "Susu sapi"},
			{x: "ジュース", y: "ジュース", z: "Jus"},
			{x: "ビール", y: "ビール", z: "Bir"},
			{x: "お酒", y: "おさけ", z: "Sake"},
			{x: "たばこ", y: "たばこ", z: "Rokok"},
			{x: "手紙", y: "てがみ", z: "Surat"},
			{x: "レポート", y: "レポート", z: "Laporan"},
			{x: "写真", y: "しゃしん", z: "Foto"},
			{x: "ビデオ", y: "ビデオ", z: "Video"},
			{x: "店", y: "みせ", z: "Toko"},
			{x: "庭", y: "にわ", z: "Halaman"},
			{x: "宿題", y: "しくだい", z: "PR"},
			{x: "テニス", y: "テニス", z: "Tenis"},
			{x: "一緒に", y: "いっしょに", z: "Bersama-sama"},
			{x: "ちょっと", y: "ちょっと", z: "Sebentar, sedikit"},
			{x: "いつも", y: "いつも", z: "Selalu"},
			{x: "時々", y: "ときどき", z: "Kadang-kadang"},
			{x: "それから", y: "それから", z: "Kemudian, setelah itu"},
			{x: "ええ", y: "ええ", z: "Ya"},
			{x: "いいですね", y: "いいですね", z: "Bagus ya"},
			{x: "分かりました", y: "わかりました", z: "Mengerti"},
			{x: "何ですか", y: "なんですか", z: "Ada apa"},
			{x: "じゃ、また", y: "じゃ、また", z: "Sampai jumpa"},
			{x: "食べ物", y: "たべもの", z: "Makanan"},
			{x: "きゅうり", y: "きゅうり", z: "Timun"},
			{x: "トマト", y: "トマト", z: "Tomat"},
			{x: "なす", y: "なす", z: "Terong"},
			{x: "豆", y: "まめ", z: "Kacang-kacangan"},
			{x: "キャベツ", y: "キャベツ", z: "Kol"},
			{x: "ねぎ", y: "ねぎ", z: "Bawang"},
			{x: "白菜", y: "はくさい", z: "Sawi putih"},
			{x: "ほうれん草", y: "ほうれんそう", z: "Bayam"},
			{x: "レタス", y: "レタス", z: "Letas"},
			{x: "じゃがいも", y: "じゃがいも", z: "Kentang"},
			{x: "だいこん", y: "だいこん", z: "Lobak"},
			{x: "玉ねぎ", y: "たまねぎ", z: "Bawang bombay"},
			{x: "にんじん", y: "にんじん", z: "Wortel"},
			{x: "いちご", y: "いちご", z: "Stroberi"},
			{x: "もも", y: "もも", z: "Buah persik"},
			{x: "すいか", y: "すいか", z: "Semangka"},
			{x: "ぶどう", y: "ぶどう", z: "Anggur"},
			{x: "なし", y: "なし", z: "Pir"},
			{x: "かき", y: "かき", z: "Kesemek"},
			{x: "みかん", y: "みかん", z: "Jeruk"},
			{x: "りんご", y: "りんご", z: "Apel"},
			{x: "バナナ", y: "バナナ", z: "Pisang"},
			{x: "牛肉", y: "ぎゅうにく", z: "Daging sapi"},
			{x: "鶏肉", y: "とりにく", z: "Daging ayam"},
			{x: "豚肉", y: "ぶたにく", z: "Daging babi"},
			{x: "米", y: "こめ", z: "Beras"},
			{x: "ソーセージ", y: "ソーセージ", z: "Sosis"},
			{x: "ハム", y: "ハム", z: "Daging ham"},
			{x: "卵", y: "たまご", z: "Telur"},
			{x: "あじ", y: "あじ", z: "Ikan aji"},
			{x: "いわし", y: "いわし", z: "Ikan sarden"},
			{x: "さば", y: "さば", z: "Ikan kembung, ikan saba"},
			{x: "さんま", y: "さんま", z: "Ikan sauri"},
			{x: "さけ", y: "さけ", z: "Ikan salmon"},
			{x: "まぐろ", y: "まぐろ", z: "Ikan tuna"},
			{x: "たい", y: "たい", z: "Ikan kakap merah"},
			{x: "たら", y: "たら", z: "Ikan gabus"},
			{x: "えび", y: "えび", z: "Udang"},
			{x: "かに", y: "かに", z: "Kepiting"},
			{x: "いか", y: "いか", z: "Cumi"},
			{x: "たこ", y: "たこ", z: "Gurita"},
			{x: "かい", y: "かい", z: "Kerang"}
		]
	},
	{
		id: "BAB 7",
		content: [
			{x: "切ります", y: "きります", z: "Memotong"},
			{x: "送ります", y: "おくります", z: "Mengirim"},
			{x: "あげます", y: "あげます", z: "Memberi"},
			{x: "もらいます", y: "もらいます", z: "Menerima"},
			{x: "貸します", y: "かします", z: "Meminjamkan"},
			{x: "借ります", y: "かります", z: "Meminjam"},
			{x: "教えます", y: "おしえます", z: "Mengajar, memberi tahu"},
			{x: "習います", y: "ならいます", z: "Belajar, berlatih"},
			{x: "かけます", y: "かけます", z: "Menelpon"},
			{x: "手", y: "て", z: "Tangan"},
			{x: "はし", y: "はし", z: "Sumpit"},
			{x: "スプーン", y: "スプーン", z: "Sendok"},
			{x: "ナイフ", y: "ナイフ", z: "Pisau"},
			{x: "フォーク", y: "フォーク", z: "Garpu"},
			{x: "はさみ", y: "はさみ", z: "Gunting"},
			{x: "パソコン", y: "パソコン", z: "Laptop"},
			{x: "ケータイ", y: "ケータイ", z: "HP"},
			{x: "メール", y: "メール", z: "Email"},
			{x: "年賀状", y: "ねんがじょう", z: "Kartu tahun baru"},
			{x: "パンチ", y: "パンチ", z: "Pelubang kertas"},
			{x: "ホッチキス", y: "ホッチキス", z: "Stepler"},
			{x: "セロテープ", y: "セロテープ", z: "Selotip"},
			{x: "消しゴム", y: "けしゴム", z: "Penghapus karet"},
			{x: "紙", y: "かみ", z: "Kertas"},
			{x: "花", y: "はな", z: "Bunga"},
			{x: "シャツ", y: "シャツ", z: "Kemeja"},
			{x: "プレゼント", y: "プレゼント", z: "Hadiah"},
			{x: "荷物", y: "にもつ", z: "Barang bawaan"},
			{x: "お金", y: "おかね", z: "Uang"},
			{x: "切符", y: "きっぷ", z: "Karcis"},
			{x: "クリスマス", y: "クリスマス", z: "Natal"},
			{x: "お父さん", y: "おとうさん", z: "Ayah"},
			{x: "お母さん", y: "おかあさん", z: "Ibu"},
			{x: "もう", y: "もう", z: "Sudah"},
			{x: "まだ", y: "まだ", z: "Belum"},
			{x: "これから", y: "これから", z: "Mulai saat ini"},
			{x: "すてきですね", y: "すてきですね", z: "Bagus ya"},
			{x: "いらっしゃい", y: "いらっしゃい", z: "Selamat datang"},
			{x: "どうぞ上がり下さい", y: "どうぞあがりください", z: "Silahkan masuk"},
			{x: "失礼します", y: "しつれいします", z: "Permisi"},
			{x: "いかがですか", y: "いかがですか", z: "Bagaimana"},
			{x: "いただきます", y: "いただきます", z: "Selamat makan"},
			{x: "ごちそうさまでした", y: "ごちそうさまでした", z: "Terimakasih hidangan nya"},
			{x: "家族", y: "かぞく", z: "Keluarga"},
			{x: "祖母", y: "そぼ", z: "Nenek"},
			{x: "祖父", y: "そふ", z: "Kakek"},
			{x: "祖父母", y: "そふぼ", z: "Kakek nenek"},
			{x: "両親", y: "りょうしん", z: "Orang tua"},
			{x: "妻", y: "つま", z: "Istri"},
			{x: "妹", y: "いもうと", z: "Adik perempuan"},
			{x: "弟", y: "おとうと", z: "Adik laki-laki"},
			{x: "兄", y: "あに", z: "Kakak laki-laki"},
			{x: "姉", y: "あね", z: "Kakak perempuan"},
			{x: "兄弟", y: "きょうだい", z: "Saudara"},
			{x: "夫", y: "おっと", z: "Suami"},
			{x: "夫婦", y: "ふうふ", z: "Suami istri"},
			{x: "娘", y: "むすめ", z: "Anak perempuan"},
			{x: "息子", y: "むすこ", z: "Anak laki-laki"}
		]
	},
	{
		id: "BAB 8",
		content: [
			{x: "ハンサムな", y: "たんぱん", z: "Tampan"},
			{x: "綺麗な", y: "きれい", z: "Cantik, bersih"},
			{x: "静かな", y: "しずかな", z: "Sepi"},
			{x: "にぎやかな", y: "にぎやかな", z: "Ramai"},
			{x: "有名な", y: "ゆうめいな", z: "Terkenal"},
			{x: "親切な", y: "しんせつな", z: "Ramah"},
			{x: "元気な", y: "げんきな", z: "Sehat"},
			{x: "暇な", y: "ひまな", z: "Senggang"},
			{x: "便利な", y: "べんりな", z: "Praktis"},
			{x: "すてきな", y: "すてきな", z: "Bagus"},
			{x: "大きい", y: "おおきい", z: "Besar"},
			{x: "小さい", y: "ちいさい", z: "Kecil"},
			{x: "新しい", y: "あたらしい", z: "Baru"},
			{x: "古い", y: "ふるい", z: "Lama, kuno"},
			{x: "いい（よい）", y: "いい", z: "Bagus"},
			{x: "悪い", y: "わるい", z: "Buruk"},
			{x: "熱い", y: "あつい", z: "Panas"},
			{x: "寒い", y: "さむい", z: "Dingin"},
			{x: "冷たい", y: "つめたい", z: "Dingin (benda)"},
			{x: "難しい", y: "むずかしい", z: "Sulit"},
			{x: "優しい", y: "やさしい", z: "Baik hati"},
			{x: "高い", y: "たかい", z: "Tinggi, mahal"},
			{x: "安い", y: "やすい", z: "Murah"},
			{x: "低い", y: "ひくい", z: "Rendah"},
			{x: "面白い", y: "おもしろい", z: "Menarik"},
			{x: "美味しい", y: "おいしい", z: "Enak"},
			{x: "忙しい", y: "いそがしい", z: "Sibuk"},
			{x: "楽しい", y: "たのしい", z: "Senang"},
			{x: "白い", y: "しろい", z: "Putih"},
			{x: "黒い", y: "くろい", z: "Hitam"},
			{x: "赤い", y: "あかい", z: "Merah"},
			{x: "青い", y: "あおい", z: "Biru"},
			{x: "桜", y: "さくら", z: "Bunga sakura"},
			{x: "山", y: "やま", z: "Gunung"},
			{x: "町", y: "まち", z: "Kota"},
			{x: "食べ物", y: "たべもの", z: "Makanan"},
			{x: "所", y: "ところ", z: "Tempat"},
			{x: "寮", y: "りょう", z: "Asrama"},
			{x: "レストラン", y: "レストラン", z: "Restoran"},
			{x: "生活", y: "せいかつ", z: "Kehidupan"},
			{x: "お仕事", y: "おしごと", z: "Pekerjaan"},
			{x: "どう", y: "どう", z: "Bagaimana"},
			{x: "どんな", y: "どんな", z: "Yang bagaimana"},
			{x: "とても", y: "とても", z: "Sangat"},
			{x: "あまり", y: "あまり", z: "Tidak begitu"},
			{x: "そして", y: "そして", z: "Kemudian"},
			{x: "お元気ですか", y: "おげんきですか", z: "Bagaimana kabarnya"},
			{x: "そうですか", y: "そうですか", z: "Benarkah"},
			{x: "もう一杯いかがですか", y: "もういっぱいいかがですか", z: "Mau tambah lagi?"},
			{x: "「いいえ」けっこうです", y: "けっこうです", z: "Terimakasih sudah cukup"},
			{x: "そろそろ失礼します", y: "しつれいします", z: "Maaf saya pamit dulu"},
			{x: "またいらっしゃって下さい", y: "またいらっしゃってください", z: "Silahkan datang lagi"},
			{x: "緑", y: "みどり", z: "Hijau"},
			{x: "紫", y: "むらさき", z: "Ungu"},
			{x: "茶色", y: "ちゃいろ", z: "Warna coklat"},
			{x: "ピンク", y: "ピンク", z: "Pink"},
			{x: "オレンジ", y: "オレンジ", z: "Orange"},
			{x: "グレー", y: "グレー", z: "Abu-abu"},
			{x: "ベージュ", y: "ベージュ", z: "Krem"},
			{x: "甘い", y: "あまい", z: "Manis"},
			{x: "辛い", y: "からい", z: "Pedas"},
			{x: "苦い", y: "にがい", z: "Pahit"},
			{x: "塩辛い", y: "しおからい", z: "Asin"},
			{x: "酸っぱい", y: "すっぱい", z: "Asam"},
			{x: "濃い", y: "こい", z: "Kental"},
			{x: "薄い", y: "うすい", z: "Hambar"},
			{x: "色", y: "いろ", z: "Warna"},
			{x: "味", y: "あじ", z: "Rasa"}
		]
	},
	{
		id: "BAB 9",
		content: [
			{x: "分かります", y: "わかります", z: "Mengerti"},
			{x: "あります", y: "あります", z: "Ada"},
			{x: "好きな", y: "すきな", z: "Suka"},
			{x: "嫌いな", y: "きらいな", z: "Benci"},
			{x: "上手な", y: "じょうずな", z: "Hebat"},
			{x: "下手な", y: "へたな", z: "Tidak mahir"},
			{x: "飲み物", y: "のみもの", z: "Minuman"},
			{x: "料理", y: "りょうり", z: "Masakan"},
			{x: "スポーツ", y: "スポーツ", z: "Olahraga"},
			{x: "野球", y: "やきゅう", z: "Baseball"},
			{x: "ダンス", y: "ダンス", z: "Dansa"},
			{x: "旅行", y: "りょこう", z: "Wisata"},
			{x: "音楽", y: "おんがく", z: "Musik"},
			{x: "歌", y: "うた", z: "Lagu"},
			{x: "クラシック", y: "クラシック", z: "Klasik"},
			{x: "ジャス", y: "ジャス", z: "Jazz"},
			{x: "コンサート", y: "コンサート", z: "Konser"},
			{x: "カラオケ", y: "カラオケ", z: "Karaoke"},
			{x: "歌舞伎", y: "かぶき", z: "Drama tradisional Jepang"},
			{x: "絵", y: "え", z: "Gambar"},
			{x: "字", y: "じ", z: "Huruf"},
			{x: "漢字", y: "かんじ", z: "Huruf kanji"},
			{x: "細かいお金", y: "こまかいおかね", z: "Uang koin"},
			{x: "チケット", y: "チケット", z: "Tiket"},
			{x: "時間", y: "じかん", z: "Waktu"},
			{x: "用事", y: "ようじ", z: "Urusan"},
			{x: "約束", y: "やくそく", z: "Janji"},
			{x: "アルバイト", y: "アルバイト", z: "Kerja parttime"},
			{x: "ご主人", y: "ごしゅじん", z: "Suami"},
			{x: "奥さん", y: "おくさん", z: "Istri"},
			{x: "よく", y: "よく", z: "Dengan baik"},
			{x: "だいたい", y: "だいたい", z: "Kira-kira"},
			{x: "たくさん", y: "たくさん", z: "Banyak"},
			{x: "すこし", y: "すこし", z: "Sedikit"},
			{x: "全然", y: "ぜんぜん", z: "Sama sekali (negative)"},
			{x: "はやく", y: "はやく", z: "Dengan cepat"},
			{x: "どうして", y: "どうして", z: "Kenapa"},
			{x: "貸してください", y: "かしてください", z: "Tolong pinjamkan"},
			{x: "いいですよ", y: "いいですよ", z: "Boleh"},
			{x: "残念ですね", y: "ざんねんですね", z: "Sayang sekali ya"},
			{x: "一緒にいかがですか", y: "いっしょにいかがですか", z: "Bagaimana kalau bersama-sama"},
			{x: "だめですか", y: "だめですか", z: "Tidak boleh ya"},
			{x: "また今度お願いします", y: "またこんどおねがいします", z: "Maaf lain kali saja"},
			{x: "恋愛", y: "れんあい", z: "Cerita cinta"},
			{x: "戦争", y: "せんそう", z: "Perang"},
			{x: "喜劇", y: "きげき", z: "Film komedi"},
			{x: "水泳", y: "すいえい", z: "Berenang"}
		]
	},
	{
		id: "BAB 10",
		content: [
			{x: "あります", y: "あります", z: "Ada (benda mati)"},
			{x: "います", y: "います", z: "Ada (benda hidup)"},
			{x: "色々な", y: "いろいろな", z: "Berbagai / macam-macam"},
			{x: "男の子", y: "おとこのこ", z: "Anak laki-laki"},
			{x: "女の子", y: "おんなのこ", z: "Anak perempuan"},
			{x: "男の人", y: "おとこのひと", z: "Orang laki-laki"},
			{x: "女の人", y: "おんなのひと", z: "Orang perempuan"},
			{x: "犬", y: "いぬ", z: "Anjing"},
			{x: "猫", y: "ねこ", z: "Kucing"},
			{x: "パンダ", y: "ぱんだ", z: "Panda"},
			{x: "象", y: "ぞう", z: "Gajah"},
			{x: "気", y: "き", z: "Perasaan"},
			{x: "物", y: "もの", z: "Barang"},
			{x: "電池", y: "でんち", z: "Baterai"},
			{x: "箱", y: "はこ", z: "Kotak"},
			{x: "スイッチ", y: "すいっち", z: "Tombol, sakelar"},
			{x: "冷蔵庫", y: "れいぞうこ", z: "Kulkas"},
			{x: "テーブル", y: "てーぶる", z: "Meja"},
			{x: "ベッド", y: "べっど", z: "Kasur"},
			{x: "棚", y: "たな", z: "Lemari"},
			{x: "ドア", y: "どあ", z: "Pintu"},
			{x: "窓", y: "まど", z: "Jendela"},
			{x: "ポスト", y: "ぽすと", z: "Kotak pos"},
			{x: "ビル", y: "びる", z: "Gedung"},
			{x: "コンビニ", y: "こんびに", z: "Minimarket"},
			{x: "公園", y: "こうえん", z: "Taman"},
			{x: "喫茶店", y: "きっさてん", z: "Kedai kopi"},
			{x: "上", y: "うえ", z: "Atas"},
			{x: "下", y: "した", z: "Bawah"},
			{x: "前", y: "まえ", z: "Depan"},
			{x: "後ろ", y: "うしろ", z: "Belakang"},
			{x: "右", y: "みぎ", z: "Kanan"},
			{x: "左", y: "ひだり", z: "Kiri"},
			{x: "中", y: "なか", z: "Tengah"},
			{x: "外", y: "そと", z: "Luar"},
			{x: "隣", y: "となり", z: "Samping"},
			{x: "近く", y: "ちかく", z: "Dekat"},
			{x: "間", y: "あいだ", z: "Diantara"},
			{x: "どうもすみません", y: "どうもすみません", z: "Terimakasih banyak"},
			{x: "ナンプラ", y: "なんぷら", z: "Kecap ikan"},
			{x: "コーナー", y: "こーなー", z: "Tempat penjualan"},
			{x: "玄関", y: "げんかん", z: "Ruang depan"},
			{x: "トイレ", y: "といれ", z: "Toilet"},
			{x: "風呂場", y: "ふろば", z: "Kamar mandi"},
			{x: "洗面所", y: "せんめんじょ", z: "Tempat cuci tangan"},
			{x: "台所", y: "だいどころ", z: "Dapur"},
			{x: "食堂", y: "しょくどう", z: "Ruang makan"},
			{x: "居間", y: "いま", z: "Ruang tamu"},
			{x: "寝室", y: "しんしつ", z: "Kamar tidur"},
			{x: "廊下", y: "ろうか", z: "Lorong/koridor"},
			{x: "ベランダ", y: "べらんだ", z: "Teras"}
		]
	},
	{
		id: "BAB 11",
		content: [
			{ x: "掛かります", y: "かかります", z: "Memerlukan waktu" },
			{ x: "休みます", y: "やすみます", z: "Istirahat" },
			{ x: "りんご", y: "りんご", z: "Apel" },
			{ x: "みかん", y: "みかん", z: "Semangka" },
			{ x: "サンドイッチ", y: "サンドイッチ", z: "Sandwich" },
			{ x: "カレーライス", y: "カレーライス", z: "Nasi kare" },
			{ x: "アイスクリーム", y: "アイスクリーム", z: "Es krim" },
			{ x: "切手", y: "きって", z: "Perangko" },
			{ x: "はがき", y: "はがき", z: "Kartu pos" },
			{ x: "封筒", y: "ふうとう", z: "Amplop" },
			{ x: "両親", y: "りょうしん", z: "Orang tua" },
			{ x: "外国", y: "がいこく", z: "Luar negeri" },
			{ x: "留学生", y: "りゅうがくせい", z: "Studi luar negeri" },
			{ x: "クラス", y: "クラス", z: "Kelas" },
			{ x: "～ぐらい", y: "～ぐらい", z: "Kira-kira" },
			{ x: "どのくらい", y: "どのくらい", z: "Berapa lama" },
			{ x: "全部で", y: "ぜんぶで", z: "Semuanya" },
			{ x: "みんな", y: "みんな", z: "Semua" },
			{ x: "～だけ", y: "～だけ", z: "Hanya, saja" },
			{ x: "かしこまりました", y: "かしこまりました", z: "Mengerti, baik" },
			{ x: "いい天気ですね", y: "いいてんきですね", z: "Cuaca nya cerah ya" },
			{ x: "お出かけですか", y: "おでかけですか", z: "Mau keluar?" },
			{ x: "いってらっしゃい", y: "いってらっしゃい", z: "Hati-hati" },
			{ x: "行ってきます", y: "いってきます", z: "Saya berangkat" },
			{ x: "船便", y: "ふなびん", z: "Pos laut" },
			{ x: "虚空便", y: "こうくうびん", z: "Pos udara" },
			{ x: "お願いします", y: "おねがいします", z: "Tolong" },
			{ x: "メニュー", y: "メニュー", z: "Menu" },
			{ x: "定食", y: "ていしょく", z: "Makanan paket" },
			{ x: "ランチ", y: "ランチ", z: "Menu makan siang" },
			{ x: "天丼", y: "てんどん", z: "Nasi dengan daging sayuran dan tempura di atasnya" },
			{ x: "お好み焼き", y: "おこのみやき", z: "Makanan goreng dengan sayuran" },
			{ x: "牛丼", y: "ぎゅうどん", z: "Nasi dengan daging sapi" },
			{ x: "焼き肉", y: "やきにく", z: "Daging panggang" },
			{ x: "野菜いため", y: "やさいいため", z: "Sayur goreng" },
			{ x: "漬物", y: "つけもの", z: "Asinan" },
			{ x: "みそ汁", y: "みそしる", z: "Sup miso" },
			{ x: "おにぎり", y: "おにぎり", z: "Nasi kepal" },
			{ x: "てんぷら", y: "てんぷら", z: "Gorengan" },
			{ x: "すし", y: "すし", z: "Nasi dengan ikan mentah" },
			{ x: "うどん", y: "うどん", z: "Mi Jepang dengan ukuran besar" },
			{ x: "そば", y: "そば", z: "Mi Jepang berwarna kehitaman" },
			{ x: "ラーメン", y: "ラーメン", z: "Ramen" },
			{ x: "焼きそば", y: "やきそば", z: "Mi goreng Jepang" },
			{ x: "カレーライス", y: "カレーライス", z: "Nasi kare" },
			{ x: "ハンバーグ", y: "ハンバーグ", z: "Hamburg" },
			{ x: "コロッケ", y: "コロッケ", z: "Kroket" },
			{ x: "えびフライ", y: "えびふらい", z: "Udang goreng tepung" },
			{ x: "フライドチキン", y: "ふらいどちきん", z: "Ayam goreng" },
			{ x: "サラダ", y: "サラダ", z: "Salad" },
			{ x: "スープ", y: "スープ", z: "Sup" },
			{ x: "スパゲッティ", y: "スパゲッティ", z: "Spaghetti" },
			{ x: "ピザ", y: "ピザ", z: "Pizza" },
			{ x: "ハンバーガー", y: "ハンバーガー", z: "Hamburger" },
			{ x: "サンドイッチ", y: "サンドイッチ", z: "Sandwich" },
			{ x: "トースト", y: "トースト", z: "Roti panggang" },
			{ x: "コーヒー", y: "コーヒー", z: "Kopi" },
			{ x: "紅茶", y: "こうちゃ", z: "Teh" },
			{ x: "ココア", y: "ココア", z: "Minuman coklat" },
			{ x: "ジュース", y: "ジュース", z: "Jus" },
			{ x: "コーラ", y: "コーラ", z: "Coca Cola" }
		]
	},
	{
		id: "BAB 12",
		content: [
			{ x: "簡単な", y: "かんたんな", z: "Mudah" },
			{ x: "遠い", y: "とおい", z: "Jauh" },
			{ x: "近い", y: "ちかい", z: "Dekat" },
			{ x: "早い", y: "はやい", z: "Cepat" },
			{ x: "遅い", y: "おそい", z: "Lambat" },
			{ x: "多い", y: "おおい", z: "Banyak" },
			{ x: "少ない", y: "すくない", z: "Sedikit" },
			{ x: "暖かい", y: "あたたかい", z: "Hangat" },
			{ x: "涼しい", y: "すずしい", z: "Sejuk" },
			{ x: "甘い", y: "あまい", z: "Manis" },
			{ x: "辛い", y: "からい", z: "Pedas" },
			{ x: "重い", y: "おもい", z: "Berat" },
			{ x: "軽い", y: "かるい", z: "Ringan" },
			{ x: "いい", y: "いい", z: "Bagus" },
			{ x: "季節", y: "きせつ", z: "Musim" },
			{ x: "春", y: "はる", z: "Musim semi" },
			{ x: "夏", y: "なつ", z: "Musim panas" },
			{ x: "秋", y: "あき", z: "Musim gugur" },
			{ x: "冬", y: "ふゆ", z: "Musim dingin" },
			{ x: "天気", y: "てんき", z: "Cuaca" },
			{ x: "雨", y: "あめ", z: "Hujan" },
			{ x: "雪", y: "ゆき", z: "Salju" },
			{ x: "曇り", y: "くもり", z: "Mendung" },
			{ x: "ホテル", y: "ホテル", z: "Hotel" },
			{ x: "空港", y: "くうこう", z: "Bandara" },
			{ x: "海", y: "うみ", z: "Laut" },
			{ x: "世界", y: "せかい", z: "Dunia" },
			{ x: "パーティー", y: "パーティー", z: "Pesta" },
			{ x: "「お」祭り", y: "おまつり", z: "Perayaan" },
			{ x: "すき焼き", y: "すきやき", z: "Sukiyaki" },
			{ x: "さしみ", y: "さしみ", z: "Sashimi" },
			{ x: "豚肉", y: "ぶたにく", z: "Daging babi" },
			{ x: "鶏肉", y: "とりにく", z: "Daging ayam" },
			{ x: "牛肉", y: "ぎゅうにく", z: "Daging sapi" },
			{ x: "レモン", y: "レモン", z: "Lemon" },
			{ x: "生け花", y: "いけばな", z: "Seni merangkai bunga" },
			{ x: "紅葉", y: "もみじ", z: "Daun maple/momiji" },
			{ x: "どちら", y: "どちら", z: "Di sebelah mana" },
			{ x: "どちらも", y: "どちらも", z: "Di sebelah mana pun" },
			{ x: "一番", y: "いちばん", z: "Paling" },
			{ x: "ずっと", y: "ずっと", z: "Terus menerus" },
			{ x: "初めて", y: "はじめて", z: "Pertama" },
			{ x: "ただいま", y: "ただいま", z: "Saya pulang" },
			{ x: "お帰りなさい", y: "おかえりなさい", z: "Selamat datang" },
			{ x: "わあ、すごい人ですね", y: "わあ、すごいひとですね", z: "Wah, banyak orang ya" },
			{ x: "疲れます", y: "つかれます", z: "Lelah" },
			{ x: "祇園祭", y: "ぎおんまつり", z: "Perayaan Gion" }
		]
	},
	{
		id: "BAB 13",
		content: [
			{ x: "遊びます", y: "あそびます", z: "Bermain" },
			{ x: "泳ぎます", y: "およぎます", z: "Berenang" },
			{ x: "迎えます", y: "むかえます", z: "Menjemput" },
			{ x: "結婚します", y: "けっこんします", z: "Menikah" },
			{ x: "買い物します", y: "かいものします", z: "Berbelanja" },
			{ x: "食事します", y: "しょくじします", z: "Makan bersama" },
			{ x: "散歩します", y: "さんぽします", z: "Jalan-jalan" },
			{ x: "大変な", y: "たいへん", z: "Sulit, sukar" },
			{ x: "欲しい", y: "ほしい", z: "Ingin" },
			{ x: "広い", y: "ひろい", z: "Luas" },
			{ x: "狭い", y: "せまい", z: "Sempit" },
			{ x: "プール", y: "プール", z: "Kolam renang" },
			{ x: "川", y: "かわ", z: "Sungai" },
			{ x: "美術", y: "びじゅつ", z: "Seni" },
			{ x: "釣り", y: "つり", z: "Memancing" },
			{ x: "スキー", y: "スキー", z: "Ski" },
			{ x: "週末", y: "しゅうまつ", z: "Akhir pekan" },
			{ x: "「お」正月", y: "おしょうがつ", z: "Tahun baru" },
			{ x: "～ごろ", y: "～ごろ", z: "~kira-kira" },
			{ x: "何か", y: "なにか", z: "Sesuatu" },
			{ x: "どこか", y: "どこか", z: "Suatu tempat" },
			{ x: "のどが乾きます", y: "かわきます", z: "Haus" },
			{ x: "お腹がすきます", y: "おなかがすきます", z: "Lapar" },
			{ x: "そうしましょう", y: "そうしましょう", z: "Ya mari" },
			{ x: "ご注文は", y: "ごちゅうもんは", z: "Mau pesan apa?" },
			{ x: "定食", y: "ていしょく", z: "Makanan paket" },
			{ x: "「少々」お待ち下さい", y: "しょうしょうおまちください", z: "Tolong tunggu sebentar" },
			{ x: "別々に", y: "べつべつに", z: "Sendiri-sendiri" },
			{ x: "博物館", y: "はくぶつかん", z: "Museum" },
			{ x: "美術館", y: "びじゅつかん", z: "Gedung kesenian" },
			{ x: "図書館", y: "としょかん", z: "Perpustakaan" },
			{ x: "映画館", y: "えいがかん", z: "Bioskop" },
			{ x: "動物園", y: "どうぶつえん", z: "Kebun binatang" },
			{ x: "植物園", y: "しょくぶつえん", z: "Kebun raya" },
			{ x: "遊園地", y: "ゆうえんち", z: "Taman bermain" },
			{ x: "お寺", y: "おてら", z: "Kuil, wihara (Budha)" },
			{ x: "神社", y: "じんじゃ", z: "Kuil (Shinto)" },
			{ x: "教会", y: "きょうかい", z: "Gereja" },
			{ x: "モスク", y: "モスク", z: "Masjid" },
			{ x: "体育館", y: "たいいくかん", z: "Gedung olahraga" },
			{ x: "公園", y: "こうえん", z: "Taman" },
			{ x: "大使館", y: "たいしかん", z: "Gedung kedutaan" },
			{ x: "入国管理局", y: "にゅうこくかんりきょく", z: "Gedung imigrasi" },
			{ x: "市役所", y: "しやくしょ", z: "Kantor balai kota" },
			{ x: "警察所", y: "けいさつしょ", z: "Kantor polisi" },
			{ x: "交番", y: "こうばん", z: "Pos polisi" },
			{ x: "消防署", y: "しょうぼうしょ", z: "Kantor damkar" },
			{ x: "駐車場", y: "ちゅうしゃじょう", z: "Tempat parkir" },
			{ x: "大学", y: "だいがく", z: "Universitas" },
			{ x: "高校", y: "こうこう", z: "SMA" },
			{ x: "中学校", y: "ちゅうがっこう", z: "SMP" },
			{ x: "小学校", y: "しょうがっこう", z: "SD" },
			{ x: "幼稚園", y: "ようちえん", z: "TK" },
			{ x: "肉屋", y: "にくや", z: "Toko daging" },
			{ x: "パン屋", y: "パンや", z: "Toko roti" },
			{ x: "魚屋", y: "さかなや", z: "Toko ikan" },
			{ x: "酒屋", y: "さかや", z: "Toko minuman keras" },
			{ x: "八百屋", y: "やおや", z: "Toko sayur" },
			{ x: "喫茶店", y: "きっさてん", z: "Kedai kopi" },
			{ x: "コンビニ", y: "コンビニ", z: "Minimarket" },
			{ x: "スーパ", y: "スーパ", z: "Supermarket" },
			{ x: "デパート", y: "デパート", z: "Departemen store" }
		]
	},
	{
		id: "BAB 14",
		content: [
			{ x: "つけます", y: "つけます", z: "Menyalakan" },
			{ x: "消します", y: "けします", z: "Mematikan, menghapus" },
			{ x: "開けます", y: "あけます", z: "Membuka" },
			{ x: "閉めます", y: "しめます", z: "Menutup" },
			{ x: "急ぎます", y: "いそぎます", z: "Bergegas" },
			{ x: "待ちます", y: "まちます", z: "Menunggu" },
			{ x: "持ちます", y: "もちます", z: "Membawa" },
			{ x: "取ります", y: "とります", z: "Mengambil" },
			{ x: "手伝います", y: "てつだいます", z: "Membantu" },
			{ x: "呼びます", y: "よびます", z: "Memanggil" },
			{ x: "話します", y: "はなします", z: "Berbicara" },
			{ x: "使います", y: "つかいます", z: "Menggunakan" },
			{ x: "止めます", y: "とめます", z: "Berhenti" },
			{ x: "見せます", y: "みせます", z: "Memperlihatkan" },
			{ x: "教えます", y: "おしえます", z: "Mengajarkan, memberitahu" },
			{ x: "座ります", y: "すわります", z: "Duduk" },
			{ x: "立ちます", y: "たちます", z: "Berdiri" },
			{ x: "入ります", y: "はいります", z: "Masuk" },
			{ x: "出ます", y: "でます", z: "Keluar" },
			{ x: "降ります", y: "ふります", z: "Turun" },
			{ x: "コピーします", y: "コピーします", z: "Mengkopi" },
			{ x: "電気", y: "でんき", z: "Listrik" },
			{ x: "エアコン", y: "エアコン", z: "AC" },
			{ x: "パスポート", y: "パスポート", z: "Paspor" },
			{ x: "名前", y: "なまえ", z: "Nama" },
			{ x: "住所", y: "じゅうしょ", z: "Alamat" },
			{ x: "地図", y: "ちず", z: "Peta" },
			{ x: "塩", y: "しお", z: "Garam" },
			{ x: "砂糖", y: "さとう", z: "Gula" },
			{ x: "問題", y: "もんだい", z: "Masalah, soal" },
			{ x: "答え", y: "こたえ", z: "Jawaban" },
			{ x: "読み方", y: "よみかた", z: "Cara baca" },
			{ x: "～方", y: "～かた", z: "~cara" },
			{ x: "まっすぐ", y: "まっすぐ", z: "Lurus, terus" },
			{ x: "ゆっくり", y: "ゆっくり", z: "Pelan-pelan" },
			{ x: "すぐ", y: "すぐ", z: "Segera" },
			{ x: "また", y: "また", z: "Lagi" },
			{ x: "あとで", y: "あとで", z: "Nanti" },
			{ x: "もうすこし", y: "もうすこし", z: "Sedikit lagi" },
			{ x: "もう～", y: "もう～", z: "Lagi~" },
			{ x: "さあ", y: "さあ", z: "Mari" },
			{ x: "あれ？", y: "あれ？", z: "Ah?" },
			{ x: "これでお願いします", y: "これでおねがいします", z: "Minta dengan ini" },
			{ x: "お釣り", y: "おつり", z: "Uang kembalian" },
			{ x: "切符売り場", y: "きっぷうりば", z: "Tempat penjualan tiket" },
			{ x: "自動券売機", y: "じどけんばいき", z: "Mesin penjual tiket otomatis" },
			{ x: "精算機", y: "せいさんき", z: "Alat penghitung otomatis" },
			{ x: "改札口", y: "かいさつぐち", z: "Pintu pemeriksaan karcis" },
			{ x: "入口", y: "いりぐち", z: "Pintu keluar" },
			{ x: "東口", y: "ひがしぐち", z: "Pintu timur" },
			{ x: "西口", y: "にしぐち", z: "Pintu barat" },
			{ x: "南口", y: "みなみぐち", z: "Pintu selatan" },
			{ x: "北口", y: "きたぐち", z: "Pintu utara" },
			{ x: "中央口", y: "ちゅうおうぐち", z: "Pintu tengah" },
			{ x: "売店", y: "ばいてん", z: "Kios, kedai" },
			{ x: "コインロッカー", y: "コインロッカー", z: "Koin loker" },
			{ x: "タクシー乗り場", y: "タクシーのりば", z: "Tempat naik taksi" },
			{ x: "バスターミナル", y: "バスターミナル", z: "Terminal bis" },
			{ x: "バス停", y: "バスてい", z: "Halte bis" },
			{ x: "特急", y: "とっきゅう", z: "Kereta api super cepat" },
			{ x: "急行", y: "きゅうこう", z: "Kereta api cepat" },
			{ x: "快速", y: "かいそく", z: "Kereta api cepat lewat pinggir kota" },
			{ x: "準急", y: "じゅんきゅう", z: "Kereta api semi cepat" },
			{ x: "普通", y: "ふつう", z: "Kereta api biasa" },
			{ x: "時刻表", y: "じこくひょう", z: "Jadwal keberangkatan" },
			{ x: "定期券", y: "ていきけん", z: "Kartu langganan berjangka" },
			{ x: "回数券", y: "かいすうけん", z: "Karcis kupon" },
			{ x: "片道", y: "かたみち", z: "Sekali jalan" },
			{ x: "往復", y: "おうふく", z: "Pulang pergi" }
		]
	},
	{
		id: "BAB 15",
		content: [
			{ x: "置きます", y: "おきます", z: "Meletakkan" },
			{ x: "作ります", y: "つくります", z: "Membuat" },
			{ x: "売ります", y: "うります", z: "Menjual" },
			{ x: "知ります", y: "しります", z: "Mengetahui" },
			{ x: "住みます", y: "すみます", z: "Tinggal" },
			{ x: "研究します", y: "けんきゅうします", z: "Meneliti" },
			{ x: "資料", y: "しりょう", z: "Bahan, data" },
			{ x: "カタログ", y: "カタログ", z: "Katalog" },
			{ x: "服", y: "ふく", z: "Pakaian" },
			{ x: "製品", y: "せいひん", z: "Produk" },
			{ x: "ソフト", y: "ソフト", z: "Perangkat lunak" },
			{ x: "電気辞書", y: "でんきじしょ", z: "Kamus elektronik" },
			{ x: "経済", y: "けいざい", z: "Ekonomi" },
			{ x: "歯医者", y: "はいしゃ", z: "Dokter gigi" },
			{ x: "独身", y: "どくしん", z: "Bujangan" },
			{ x: "皆さん", y: "みなさん", z: "Semuanya" },
			{ x: "思い出します", y: "おもいだします", z: "Teringat, terbayang" },
			{ x: "いらっしゃいます", y: "いらっしゃいます", z: "Selamat datang" },
			{ x: "会社員", y: "かいしゃいん", z: "Karyawan perusahaan" },
			{ x: "公務員", y: "こうむいん", z: "PNS" },
			{ x: "駅員", y: "えきいん", z: "Pegawai stasiun" },
			{ x: "銀行員", y: "ぎんこういん", z: "Pegawai bank" },
			{ x: "郵便局員", y: "ゆうびんきょくいん", z: "Pegawai kantor pos" },
			{ x: "店員", y: "てんいん", z: "Pelayan toko" },
			{ x: "調理師", y: "ちょうりし", z: "Koki" },
			{ x: "理容師", y: "りようし", z: "Tukang potong rambut" },
			{ x: "美容師", y: "びようし", z: "Ahli kecantikan" },
			{ x: "教師", y: "きょうし", z: "Guru" },
			{ x: "弁護士", y: "べんごし", z: "Pengacara" },
			{ x: "研究者", y: "けんきゅうしゃ", z: "Peneliti" },
			{ x: "医者", y: "いしゃ", z: "Dokter" },
			{ x: "看護師", y: "かんごし", z: "Perawat" },
			{ x: "運転手", y: "うんてんしゅ", z: "Sopir" },
			{ x: "警察官", y: "けいさつかん", z: "Polisi" },
			{ x: "外交官", y: "がいこうかん", z: "Diplomat" },
			{ x: "政治家", y: "せいじか", z: "Politikus" },
			{ x: "画家", y: "がか", z: "Pelukis" },
			{ x: "作家", y: "さっか", z: "Pengarang" },
			{ x: "音楽家", y: "おんがくか", z: "Musisi" },
			{ x: "建築家", y: "けんちくか", z: "Arsitek" },
			{ x: "エンジニア", y: "エンジニア", z: "Insinyur" },
			{ x: "デザイナー", y: "デザイナー", z: "Desainer" },
			{ x: "ジャーナリスト", y: "ジャーナリスト", z: "Wartawan" },
			{ x: "歌手", y: "かしゅ", z: "Penyanyi" },
			{ x: "俳優", y: "はいゆう", z: "Artis" },
			{ x: "スポーツ選手", y: "スポーツせんしゅ", z: "Atlit" }
		]
	},
	{
		id: "BAB 16",
		content: [
			{ x: "乗ります", y: "のります", z: "Naik" },
			{ x: "降ります", y: "おります", z: "Turun" },
			{ x: "乗り換えます", y: "のりかえます", z: "Pindah kendaraan" },
			{ x: "浴びます", y: "あびます", z: "Mandi" },
			{ x: "入れます", y: "いれます", z: "Memasukkan" },
			{ x: "出します", y: "だします", z: "Mengeluarkan, membuang" },
			{ x: "下ろします", y: "おろします", z: "Mengambil, menurunkan" },
			{ x: "入ります", y: "はいります", z: "Masuk" },
			{ x: "出ます", y: "でます", z: "Keluar" },
			{ x: "押します", y: "おします", z: "Menekan, mendorong" },
			{ x: "飲みます", y: "のみます", z: "Minum" },
			{ x: "始めます", y: "はじめます", z: "Memulai" },
			{ x: "見学します", y: "けんがくします", z: "Meninjau" },
			{ x: "電話します", y: "でんわします", z: "Menelpon" },
			{ x: "若い", y: "わかい", z: "Muda" },
			{ x: "長い", y: "ながい", z: "Panjang" },
			{ x: "短い", y: "みじかい", z: "Pendek" },
			{ x: "明るい", y: "あかるい", z: "Terang" },
			{ x: "暗い", y: "くらい", z: "Gelap" },
			{ x: "体", y: "からだ", z: "Tubuh, badan" },
			{ x: "頭", y: "あたま", z: "Kepala" },
			{ x: "髪", y: "かみ", z: "Rambut" },
			{ x: "顔", y: "かお", z: "Wajah" },
			{ x: "目", y: "め", z: "Mata" },
			{ x: "耳", y: "みみ", z: "Telinga" },
			{ x: "花", y: "はな", z: "Hidung" },
			{ x: "口", y: "くち", z: "Mulut" },
			{ x: "歯", y: "は", z: "Gigi" },
			{ x: "お腹", y: "おなか", z: "Perut" },
			{ x: "足", y: "あし", z: "Kaki" },
			{ x: "背", y: "せ", z: "Punggung" },
			{ x: "サービス", y: "サービス", z: "Pelayanan" },
			{ x: "ジョギング", y: "ジョギング", z: "Jogging" },
			{ x: "シャワー", y: "シャワー", z: "Shower" },
			{ x: "緑", y: "みどり", z: "Hijau" },
			{ x: "どうやって", y: "どうやって", z: "Dengan cara bagaimana" },
			{ x: "どの～", y: "どの～", z: "Tuan" },
			{ x: "どれ", y: "どれ", z: "Yang mana" },
			{ x: "すごいですね", y: "すごいですね", z: "Hebat ya" },
			{ x: "「いいえ、」まだまだです", y: "「いいえ、」まだまだです", z: "Belum memuaskan" },
			{ x: "お引き出しですか", y: "おひきだしですか", z: "Apa mau mengambil uang" },
			{ x: "まず", y: "まず", z: "Pertama-tama" },
			{ x: "次に", y: "つぎに", z: "Selanjutnya" },
			{ x: "キャッシュカード", y: "キャッシュカード", z: "Kartu ATM" },
			{ x: "暗証番号", y: "あんしょうばんごう", z: "Nomor PIN" },
			{ x: "金額", y: "きんがく", z: "Jumlah uang" },
			{ x: "確認", y: "かくにん", z: "Memastikan" },
			{ x: "ボタン", y: "ボタン", z: "Tombol" }
		]
	},
	{
		id: "BAB 17",
		content: [
			{ x: "覚えます", y: "おぼえます", z: "Mengingat" },
			{ x: "忘れます", y: "わすれます", z: "Lupa" },
			{ x: "亡くします", y: "なくします", z: "Menghilangkan" },
			{ x: "払います", y: "はらいます", z: "Membayar" },
			{ x: "返します", y: "かえします", z: "Mengembalikan" },
			{ x: "出かけます", y: "でかけます", z: "Keluar" },
			{ x: "脱ぎます", y: "ぬぎます", z: "Melepas (pakaian)" },
			{ x: "持って行きます", y: "もっていきます", z: "Membawa pergi" },
			{ x: "持って来ます", y: "もってきます", z: "Membawa datang" },
			{ x: "心配します", y: "しんぱいします", z: "Khawatir" },
			{ x: "残業します", y: "ざんぎょうします", z: "Lembur" },
			{ x: "出張します", y: "しゅっちょうします", z: "Dinas" },
			{ x: "大切な", y: "たいせつな", z: "Penting" },
			{ x: "大丈夫な", y: "だいじょうぶな", z: "Tidak apa-apa" },
			{ x: "危ない", y: "あぶない", z: "Bahaya" },
			{ x: "禁煙", y: "きんえん", z: "Dilarang merokok" },
			{ x: "保険証", y: "ほけんしょう", z: "Kartu asuransi kesehatan" },
			{ x: "熱", y: "ねつ", z: "Demam" },
			{ x: "病気", y: "びょうき", z: "Sakit" },
			{ x: "薬", y: "くすり", z: "Obat" },
			{ x: "「お」ふろ", y: "おふろ", z: "Kamar mandi" },
			{ x: "上着", y: "うわぎ", z: "Jaket" },
			{ x: "下着", y: "したぎ", z: "Pakaian dalam" },
			{ x: "～までに", y: "までに", z: "Sampai dengan" },
			{ x: "ですから", y: "ですから", z: "Oleh karena itu" },
			{ x: "どうしましたか", y: "どうしましたか", z: "Kenapa/ada masalah apa?" },
			{ x: "のど", y: "のど", z: "Tenggorokan" },
			{ x: "痛いです", y: "いたいです", z: "Sakit" },
			{ x: "かぜ", y: "かぜ", z: "Masuk angin" },
			{ x: "それから", y: "それから", z: "Kemudian" },
			{ x: "お大事に", y: "おだいじに", z: "Semoga lekas sembuh" },
			{ x: "頭が痛い", y: "あたまがいたい", z: "Sakit kepala" },
			{ x: "お腹が痛い", y: "おなかがいたい", z: "Sakit perut" },
			{ x: "歯が痛い", y: "はがいたい", z: "Sakit gigi" },
			{ x: "熱があります", y: "ねつがあります", z: "Demam" },
			{ x: "せきが出ます", y: "せきがでます", z: "Batuk" },
			{ x: "鼻水が出ます", y: "はなみずがでます", z: "Pilek" },
			{ x: "血が出ます", y: "ちがでます", z: "Berdarah" },
			{ x: "吐き気がします", y: "はきけがします", z: "Mual, mau muntah" },
			{ x: "めまいがします", y: "めまいがします", z: "Pening, pusing" },
			{ x: "下痢をします", y: "げりをします", z: "Diare" },
			{ x: "便秘をします", y: "べんぴをします", z: "Sembelit" },
			{ x: "けがをします", y: "けがをします", z: "Terluka" },
			{ x: "やけどをします", y: "やけどをします", z: "Terbakar" },
			{ x: "食欲がありません", y: "しょくよくがありません", z: "Tidak nafsu makan" },
			{ x: "肩がこります", y: "かたがこります", z: "Bahu pegal" },
			{ x: "体がだるい", y: "からだがだるい", z: "Badan lemas" },
			{ x: "かゆい", y: "かゆい", z: "Gatal" },
			{ x: "あご", y: "あご", z: "Dagu" },
			{ x: "むね", y: "むね", z: "Dada" },
			{ x: "ゆび", y: "ゆび", z: "Jari" },
			{ x: "ひじ", y: "ひじ", z: "Sikut" },
			{ x: "つめ", y: "つめ", z: "Kuku" },
			{ x: "ひざ", y: "ひざ", z: "Lutut" },
			{ x: "骨", y: "ほね", z: "Tulang" },
			{ x: "しり", y: "しり", z: "Pantat" },
			{ x: "こし", y: "こし", z: "Pinggang" },
			{ x: "かた", y: "かた", z: "Bahu" },
			{ x: "せなか", y: "せなか", z: "Punggung" },
			{ x: "うで", y: "うで", z: "Lengan" },
			{ x: "かぜ", y: "かぜ", z: "Masuk angin" },
			{ x: "インフルエンザ", y: "インフルエンザ", z: "Influenza" },
			{ x: "盲腸", y: "もうちょう", z: "Usus buntu" },
			{ x: "ぎっくり腰", y: "ぎっくりごし", z: "Sakit pinggang" },
			{ x: "ねんざ", y: "ねんざ", z: "Kesleo" },
			{ x: "骨折", y: "こっせつ", z: "Patah tulang" },
			{ x: "二日酔い", y: "ふつかよい", z: "Efek setelah minum" }
		]
	},
	{
		id: "BAB 18",
		content: [
			{ x: "できます", y: "できます", z: "Bisa, dapat" },
			{ x: "洗います", y: "あらいます", z: "Mencuci" },
			{ x: "弾きます", y: "ひきます", z: "Bermain" },
			{ x: "歌います", y: "うたいます", z: "Menyanyi" },
			{ x: "集めます", y: "あつめます", z: "Mengumpulkan" },
			{ x: "捨てます", y: "すてます", z: "Membuang" },
			{ x: "換えます", y: "かえます", z: "Mengganti" },
			{ x: "運転します", y: "うんてんします", z: "Menyetir, mengendarai" },
			{ x: "予約します", y: "よやくします", z: "Memesan" },
			{ x: "ピアノ", y: "ピアノ", z: "Piano" },
			{ x: "趣味", y: "しゅみ", z: "Hobi" },
			{ x: "日記", y: "にっき", z: "Diary" },
			{ x: "お祈り", y: "おいのり", z: "Berdoa" },
			{ x: "課長", y: "かちょう", z: "Kepala seksi" },
			{ x: "部長", y: "ぶちょう", z: "Kepala bagian" },
			{ x: "社長", y: "しゃちょう", z: "Direktur" },
			{ x: "動物", y: "どうぶつ", z: "Binatang" },
			{ x: "馬", y: "うま", z: "Kuda" },
			{ x: "インターネット", y: "インターネット", z: "Internet" },
			{ x: "特に", y: "とくに", z: "Terutama" },
			{ x: "へえ", y: "へえ", z: "Betul ya, benar ya" },
			{ x: "それは面白いですね", y: "それはおもしろいですね", z: "Itu menarik ya" },
			{ x: "なかなか", y: "なかなか", z: "Jarang, tidak mudah" },
			{ x: "本当ですか", y: "ほんとうですか", z: "Benarkah" },
			{ x: "故郷", y: "ふるさと", z: "Kampung halaman" },
			{ x: "飛びます", y: "とびます", z: "Terbang" },
			{ x: "跳びます", y: "とびます", z: "Meloncat" },
			{ x: "登ります", y: "のぼります", z: "Memanjat" },
			{ x: "走ります", y: "はしります", z: "Berlari" },
			{ x: "泳ぎます", y: "およぎます", z: "Berenang" },
			{ x: "もぐります", y: "もぐります", z: "Menyelam" },
			{ x: "飛び込みます", y: "とびこみます", z: "Terjun" },
			{ x: "逆立ちします", y: "さかだちします", z: "Jungkir balik" },
			{ x: "はいます", y: "はいます", z: "Merayap" },
			{ x: "けります", y: "けります", z: "Menendang" },
			{ x: "振ります", y: "ふります", z: "Melambaikan" },
			{ x: "持ち上げます", y: "もちあげます", z: "Mengangkat" },
			{ x: "投げます", y: "なげます", z: "Melempar" },
			{ x: "たたきます", y: "たたきます", z: "Memukul" },
			{ x: "引きます", y: "ひきます", z: "Menarik" },
			{ x: "押します", y: "おします", z: "Mendorong" },
			{ x: "曲げます", y: "まげます", z: "Membengkokkan" },
			{ x: "伸ばします", y: "のばします", z: "Meluruskan" },
			{ x: "転びます", y: "ころびます", z: "Jatuh" },
			{ x: "振り向きます", y: "ふりむきます", z: "Menegok ke belakang" }
		]
	},
	{
		id: "BAB 19",
		content: [
			{ x: "登ります", y: "のぼります", z: "Naik" },
			{ x: "泊まります", y: "とまります", z: "Menginap" },
			{ x: "掃除します", y: "そうじします", z: "Membersihkan" },
			{ x: "洗濯します", y: "せんたくします", z: "Mencuci" },
			{ x: "眠い", y: "ねむい", z: "Mengantuk" },
			{ x: "強い", y: "つよい", z: "Kuat" },
			{ x: "弱い", y: "よわい", z: "Lemah" },
			{ x: "練習", y: "れんしゅう", z: "Latihan" },
			{ x: "ゴルフ", y: "ゴルフ", z: "Golf" },
			{ x: "ひ", y: "ひ", z: "Hari" },
			{ x: "調子", y: "ちょうし", z: "Kondisi" },
			{ x: "一度", y: "いちど", z: "Sekali" },
			{ x: "一度も", y: "いちども", z: "Sekalipun (bentuk negative)" },
			{ x: "だんだん", y: "だんだん", z: "Lama kelamaan, berangsur angsur" },
			{ x: "もうすぐ", y: "もうすぐ", z: "Sebentar lagi" },
			{ x: "おかげさまで", y: "おかげさまで", z: "Berkat doa anda" },
			{ x: "でも", y: "でも", z: "Tetapi" },
			{ x: "乾杯", y: "かんぱい", z: "Toast" },
			{ x: "ダイエット", y: "ダイエット", z: "Diet" },
			{ x: "無理な", y: "むりな", z: "Tidak mungkin" },
			{ x: "体にいい", y: "からだにいい", z: "Bagus untuk tubuh" },
			{ x: "伝統文化", y: "でんとうぶんか", z: "Kebudayaan tradisional" },
			{ x: "娯楽", y: "ごらく", z: "Hiburan" },
			{ x: "茶道（お茶）", y: "さどう（おちゃ）", z: "Upacara minum the" },
			{ x: "華道（生け花）", y: "かどう（いけばな）", z: "Seni merangkai bunga" },
			{ x: "書道", y: "しょどう", z: "Seni melukis huruf jepang" },
			{ x: "歌舞伎", y: "かぶき", z: "Drama tradisional" },
			{ x: "能", y: "のう", z: "Drama topeng tradisional" },
			{ x: "文楽", y: "ぶんらく", z: "Wayang golek tradisional" },
			{ x: "柔道", y: "じゅうどう", z: "Olahraga Judo" },
			{ x: "剣道", y: "けんどう", z: "Olahraga Kendo" },
			{ x: "漫才", y: "まんざい", z: "Lelucon" },
			{ x: "落語", y: "らくご", z: "Komedi" },
			{ x: "囲碁", y: "いご", z: "Catur China/ Jepang" },
			{ x: "将棋", y: "しょうぎ", z: "Catur Jepang" }
		]
	},
	{
		id: "BAB 20",
		content: [
			{ x: "要ります", y: "いります", z: "Membutuhkan, memerlukan" },
			{ x: "調べます", y: "しらべます", z: "Memeriksa, meneliti" },
			{ x: "修理します", y: "しゅうりします", z: "Memperbaiki" },
			{ x: "僕", y: "ぼく", z: "Saya" },
			{ x: "君", y: "きみ", z: "Kamu" },
			{ x: "～君", y: "～くん", z: "Bentuk informal さん" },
			{ x: "うん", y: "うん", z: "Iya" },
			{ x: "ううん", y: "ううん", z: "Tidak" },
			{ x: "言葉", y: "ことば", z: "Kosakata" },
			{ x: "着物", y: "きもの", z: "Kimono" },
			{ x: "ビザ", y: "ビザ", z: "Visa" },
			{ x: "初め", y: "はじめ", z: "Awal" },
			{ x: "終わり", y: "おわり", z: "Akhir" },
			{ x: "こっち", y: "こっち", z: "Disini" },
			{ x: "そっち", y: "そっち", z: "Disana" },
			{ x: "あっち", y: "あっち", z: "Disana" },
			{ x: "どっち", y: "どっち", z: "Dimana" },
			{ x: "みんなで", y: "みんなで", z: "Kita semua" },
			{ x: "～けど", y: "～けど", z: "~tetapi" },
			{ x: "よかったら", y: "よかったら", z: "Kalau mau, kalau suka" },
			{ x: "いろいろ", y: "いろいろ", z: "Macam-macam" }
		]
	},
	{
		id: "BAB 21",
		content: [
			{ x: "思います", y: "おもいます", z: "Berpikir" },
			{ x: "言います", y: "いいます", z: "Berkata" },
			{ x: "勝ちます", y: "かちます", z: "Menang" },
			{ x: "負けます", y: "まけます", z: "Kalah" },
			{ x: "あります", y: "あります", z: "Ada" },
			{ x: "役に立ちます", y: "やくにたちます", z: "Bermanfaat" },
			{ x: "動きます", y: "うごきます", z: "Bergerak" },
			{ x: "やめます", y: "やめます", z: "Berhenti (kerja)" },
			{ x: "気を付けます", y: "きをつけます", z: "Hati-hati" },
			{ x: "留学します", y: "りゅうがくします", z: "Studi di luar negeri" },
			{ x: "無駄な", y: "むだな", z: "Sia-sia" },
			{ x: "不便な", y: "ふべんな", z: "Tidak praktis" },
			{ x: "すごい", y: "すごい", z: "Hebat" },
			{ x: "本当", y: "ほんとう", z: "Benar, betul" },
			{ x: "うそ", y: "うそ", z: "Bohong" },
			{ x: "自動車", y: "じどうしゃ", z: "Mobil" },
			{ x: "交通", y: "こうつう", z: "Lalu lintas" },
			{ x: "物価", y: "ぶっか", z: "Harga barang" },
			{ x: "放送", y: "ほうそう", z: "Siaran langsung" },
			{ x: "ニュース", y: "ニュース", z: "Berita" },
			{ x: "アニメ", y: "アニメ", z: "Animasi" },
			{ x: "マンガ", y: "マンガ", z: "Komik" },
			{ x: "デザイン", y: "デザイン", z: "Desain" },
			{ x: "夢", y: "ゆめ", z: "Mimpi" },
			{ x: "天才", y: "てんさい", z: "Genius" },
			{ x: "試合", y: "しあい", z: "Pertandingan" },
			{ x: "意見", y: "いけん", z: "Pendapat" },
			{ x: "話", y: "はなし", z: "Cerita" },
			{ x: "地球", y: "ちきゅう", z: "Bumi" },
			{ x: "月", y: "つき", z: "Bulan" },
			{ x: "最近", y: "さいきん", z: "Akhir-akhir ini" },
			{ x: "多分", y: "たぶん", z: "Mungkin" },
			{ x: "きっと", y: "きっと", z: "Pasti" },
			{ x: "本当に", y: "ほんとうに", z: "Benarkah" },
			{ x: "そんなに", y: "そんなに", z: "Tidak begitu" },
			{ x: "～について", y: "～について", z: "Tentang" },
			{ x: "久しぶりですね", y: "ひさしぶりですね", z: "Lama tak jumpa ya" },
			{ x: "～でも飲みませんか", y: "～でものみませんか", z: "Bagaimana kalau kita minum" },
			{ x: "もちろん", y: "もちろん", z: "Tentu saja" },
			{ x: "もう帰らないと", y: "もうかえらないと", z: "Saya harus pulang" },
			{ x: "役職名", y: "やくしょくめい", z: "Nama-nama jabatan" },
			{ x: "国", y: "くに", z: "Negara" },
			{ x: "都道府県", y: "とどうふけん", z: "Perfektur" },
			{ x: "市", y: "し", z: "Kota" },
			{ x: "町", y: "まち", z: "Distrik, daerah" },
			{ x: "村", y: "むら", z: "Desa" },
			{ x: "首相", y: "しゅしょう", z: "Perdana menteri" },
			{ x: "知事", y: "ちじ", z: "Gubernur" },
			{ x: "市長", y: "しちょう", z: "Walikota" },
			{ x: "町長", y: "ちょうちょう", z: "Kepala daerah" },
			{ x: "村長", y: "そんちょう", z: "Kepala desa" },
			{ x: "学長", y: "がくちょう", z: "Rektor" },
			{ x: "校長", y: "こうちょう", z: "Kepala sekolah" },
			{ x: "園長", y: "えんちょう", z: "Kepala TK" },
			{ x: "会社", y: "かいしゃ", z: "Perusahaan" },
			{ x: "会長", y: "かいちょう", z: "Ketua" },
			{ x: "社長", y: "しゃちょう", z: "Direktur utama" },
			{ x: "重役", y: "じゅうやく", z: "Direktur" },
			{ x: "部長", y: "ぶちょう", z: "Kepala bagian" },
			{ x: "課長", y: "かちょう", z: "Kepala seksi" },
			{ x: "病院", y: "びょういん", z: "Rumah sakit" },
			{ x: "院長", y: "いんちょう", z: "Kepala RS" },
			{ x: "看護師長", y: "かんごしちょう", z: "Kepala perawat" },
			{ x: "銀行", y: "ぎんこう", z: "Bank" },
			{ x: "頭取", y: "とうどり", z: "Direktur bank" },
			{ x: "支店長", y: "してんちょう", z: "Kepala kantor cabang" },
			{ x: "駅", y: "えき", z: "Stasiun" },
			{ x: "駅長", y: "えきちょう", z: "Kepala stasiun" },
			{ x: "警察", y: "けいさつ", z: "Kantor polisi" },
			{ x: "署長", y: "しょちょう", z: "Kepala kantor polisi" }
		]
	},
	{
		id: "BAB 22",
		content: [
			{ x: "来ます", y: "きます", z: "Datang" },
			{ x: "はきます", y: "はきます", z: "Memakai (sepatu, celana)" },
			{ x: "かぶります", y: "かぶります", z: "Memakai (topi)" },
			{ x: "かけます", y: "かけます", z: "Memakai (dasi)" },
			{ x: "します", y: "します", z: "Melakukan" },
			{ x: "うまれます", y: "うまれます", z: "Lahir" },
			{ x: "私達", y: "わたしたち", z: "Kita/kami" },
			{ x: "コート", y: "コート", z: "Mantal" },
			{ x: "セーター", y: "セーター", z: "Sweater" },
			{ x: "スーツ", y: "スーツ", z: "Pakaian setelan" },
			{ x: "帽子", y: "ぼうし", z: "Topi" },
			{ x: "眼鏡", y: "めがね", z: "Kacamata" },
			{ x: "ケーキ", y: "ケーキ", z: "Kue" },
			{ x: "【お】弁当", y: "おべんとう", z: "Bekal" },
			{ x: "ロボット", y: "ロボット", z: "Robot" },
			{ x: "ユーモア", y: "ユーモア", z: "Humor" },
			{ x: "都合", y: "つごう", z: "Kondisi" },
			{ x: "よく", y: "よく", z: "Sering kali" },
			{ x: "えーと", y: "えーと", z: "Itu…" },
			{ x: "おめでとうございます", y: "おめでとうございます", z: "Selamat" },
			{ x: "お探しですか", y: "おさがしですか", z: "Mencari apa" },
			{ x: "では", y: "では", z: "Kalau begitu" },
			{ x: "こちら", y: "こちら", z: "Disana" },
			{ x: "家賃", y: "やちん", z: "Biaya sewa rumah" },
			{ x: "ダイニングキッチン", y: "ダイニングキッチン", z: "Ruang makan dengan dapur" },
			{ x: "和室", y: "わしつ", z: "Kamar tidur Jepang" },
			{ x: "押し入れ", y: "おしいれ", z: "Lemari dinding Jepang" },
			{ x: "布団", y: "ふとん", z: "Selimut dan kasur Jepang" },
			{ x: "万里の長城", y: "ばんりのちょうじょう", z: "Tembok besar China" },
			{ x: "衣服", y: "いふく", z: "Pakaian" },
			{ x: "ワンピース", y: "ワンピース", z: "Pakaian terusan" },
			{ x: "上着", y: "うわぎ", z: "Jas" },
			{ x: "ズボン", y: "ズボン", z: "Celana panjang" },
			{ x: "パンツ", y: "パンツ", z: "Celana pendek" },
			{ x: "ジーンズ", y: "ジーンズ", z: "Jeans" },
			{ x: "スカート", y: "スカート", z: "Rok" },
			{ x: "ブラウス", y: "ブラウス", z: "Blus" },
			{ x: "ワイシャツ", y: "ワイシャツ", z: "Kemeja" },
			{ x: "マフラー", y: "マフラー", z: "Syal/selendang" },
			{ x: "手袋", y: "てぶくろ", z: "Kaos tangan" },
			{ x: "下着", y: "したぎ", z: "Pakaian dalam" },
			{ x: "靴下", y: "くつした", z: "Kaos kaki" },
			{ x: "ストッキング", y: "ストッキング", z: "Stoking" },
			{ x: "帯", y: "おび", z: "Ikat pinggang tradisional" },
			{ x: "ぞうり", y: "ぞうり", z: "Sandal tradisional Jepang" },
			{ x: "たび", y: "たび", z: "Kaos kaki tradisional Jepang" },
			{ x: "レインコート", y: "レインコート", z: "Jas hujan" },
			{ x: "ネクタイ", y: "ネクタイ", z: "Dasi" },
			{ x: "ベルト", y: "ベルト", z: "Ikat pinggang" },
			{ x: "ハイヒール", y: "ハイヒール", z: "Sepatu hak tinggi" },
			{ x: "ブーツ", y: "ブーツ", z: "Sepatu boots" },
			{ x: "運動靴", y: "うんどうぐつ", z: "Sepatu olahraga" }
		]
	},
	{
		id: "BAB 23",
		content: [
			{ x: "聞きます", y: "ききます", z: "Mendengar" },
			{ x: "回します", y: "まわします", z: "Memutar" },
			{ x: "引きます", y: "ひきます", z: "Menarik" },
			{ x: "換えます", y: "かえます", z: "Mengubah" },
			{ x: "触ります", y: "さわります", z: "Menyentuh" },
			{ x: "曲がります", y: "まがります", z: "Belok" },
			{ x: "出ます", y: "でます", z: "Keluar" },
			{ x: "歩きます", y: "あるきます", z: "Berjalan kaki" },
			{ x: "渡ります", y: "わたります", z: "Menyebrang" },
			{ x: "寂しい", y: "さびしい", z: "Sepi" },
			{ x: "「お」湯", y: "おゆ", z: "Air panas" },
			{ x: "音", y: "おと", z: "Suara" },
			{ x: "サイズ", y: "サイズ", z: "Ukuran" },
			{ x: "故障", y: "こしょう", z: "Rusak" },
			{ x: "道", y: "みち", z: "Jalan" },
			{ x: "交差点", y: "こうさてん", z: "Perempatan" },
			{ x: "信号", y: "しんごう", z: "Lampu lalu lintas" },
			{ x: "角", y: "かど", z: "Belokan /tikungan" },
			{ x: "橋", y: "はし", z: "Jembatan" },
			{ x: "駐車場", y: "ちゅうしゃじょう", z: "Tempat parkir" },
			{ x: "建物", y: "たてもの", z: "Bangunan" },
			{ x: "道路", y: "どうろ", z: "Jalan" },
			{ x: "歩道", y: "ほどう", z: "Trotoar" },
			{ x: "車道", y: "しゃどう", z: "Jalan mobil" },
			{ x: "高速道路", y: "こうそくどうろ", z: "Jalan tol" },
			{ x: "通り", y: "どおり", z: "Jalan" },
			{ x: "横断歩道", y: "おうだんほどう", z: "Tempat menyebrang" },
			{ x: "歩道橋", y: "ほどうきょう", z: "Jembatan penyebrangan" },
			{ x: "坂", y: "さか", z: "Lereng" },
			{ x: "踏切", y: "ふみきり", z: "Rel kereta api" },
			{ x: "ガソリンスタンド", y: "ガソリンスタンド", z: "SPBU" },
			{ x: "止まれ", y: "とまれ", z: "Berhenti" },
			{ x: "進入禁止", y: "しんにゅうきんし", z: "Dilarang masuk" },
			{ x: "一方通行", y: "いっぽうつうこう", z: "Satu arah" },
			{ x: "駐車禁止", y: "ちゅうしゃきんし", z: "Dilarang parkir" },
			{ x: "右折禁止", y: "うせつきんし", z: "Dilarang belok kanan" }
		]
	},
	{
		id: "BAB 24",
		content: [
			{ x: "くれます", y: "くれます", z: "Diberikan" },
			{ x: "直します", y: "なおします", z: "Mengoreksi" },
			{ x: "連れて行きます", y: "つれていきます", z: "Mengantar pergi/ membawa" },
			{ x: "連れて来ます", y: "つれてきます", z: "Mengantar datang /membawa" },
			{ x: "送ります", y: "おくります", z: "Mengirim" },
			{ x: "紹介します", y: "しょうかいします", z: "Memperkenalkan" },
			{ x: "案内します", y: "あんないします", z: "Mengantarkan" },
			{ x: "説明します", y: "せつめいします", z: "Menjelaskan" },
			{ x: "おじいさん／おじいちゃん", y: "おじいさん／おじいちゃん", z: "Kakek" },
			{ x: "おばあさん／おばあちゃん", y: "おばあさん／おばあちゃん", z: "Nenek" },
			{ x: "準備", y: "じゅんび", z: "Persiapan" },
			{ x: "引っ越し", y: "ひっこし", z: "Pindah rumah" },
			{ x: "「お」菓子", y: "おかし", z: "Cemilan/kue" },
			{ x: "ホームステイ", y: "ホームステイ", z: "Homestay" },
			{ x: "全部", y: "ぜんぶ", z: "Semua" },
			{ x: "自分で", y: "じぶんで", z: "Diri sendiri" },
			{ x: "他に", y: "ほかに", z: "Yang lain" },
			{ x: "贈答の習慣", y: "ぞうとうのしゅうかん", z: "Tukar menukar hadiah" },
			{ x: "お年玉", y: "おとしだま", z: "Hadiah diberikan saat tahun baru" },
			{ x: "入学祝い", y: "にゅがくいわい", z: "Hadiah untuk anak yang masuk sekolah" },
			{ x: "結婚祝い", y: "けっこんいわい", z: "Hadiah perkawinan" },
			{ x: "出産祝い", y: "しゅっさんいわい", z: "Hadiah untuk orang melahirkan" },
			{ x: "お香典", y: "おこうでん", z: "Uang buat keluarga berduka" },
			{ x: "お見舞い", y: "おみまい", z: "Hadiah untuk orang sakit" },
			{ x: "卒業祝い", y: "そつぎょういわい", z: "Hadiah untuk anak tamat sekolah" }
		]
	},
	{
		id: "BAB 25",
		content: [
			{ x: "考えます", y: "かんがえます", z: "Berpikir" },
			{ x: "着きます", y: "つきます", z: "Sampai/tiba" },
			{ x: "取ります", y: "とります", z: "Mengambil" },
			{ x: "足ります", y: "たります", z: "Cukup" },
			{ x: "田舎", y: "いなか", z: "Kampung" },
			{ x: "チャンス", y: "チャンス", z: "Kesempatan" },
			{ x: "億", y: "おく", z: "Ratus juta" },
			{ x: "もし", y: "もし", z: "Kalau" },
			{ x: "意味", y: "いみ", z: "Arti" },
			{ x: "もしもし", y: "もしもし", z: "Hallo" },
			{ x: "転勤", y: "てんきん", z: "Pindah kerja ke kantor lain" },
			{ x: "事", y: "こと", z: "Hal" },
			{ x: "「色々」お世話になりました", y: "いろいろおせわになりました", z: "Terimakasih bantuan anda" },
			{ x: "暇", y: "ひま", z: "Waktu luang" },
			{ x: "頑張ります", y: "がんばります", z: "Semangat" },
			{ x: "どうぞお元気で", y: "どうぞおげんきで", z: "Semoga sehat selalu" },
			{ x: "人の一生", y: "ひとのいっしょう", z: "Seumur hidup manusia" },
			{ x: "赤ちゃん", y: "あかちゃん", z: "Bayi" },
			{ x: "子供", y: "こども", z: "Anak-anak" },
			{ x: "青年", y: "せいねん", z: "Remaja" },
			{ x: "中年", y: "ちゅうねん", z: "Paruh baya" },
			{ x: "老人", y: "ろうじん", z: "Orang tua" },
			{ x: "生まれます", y: "うまれます", z: "Lahir" },
			{ x: "保育園", y: "ほいくえん", z: "Playgroup" },
			{ x: "専門学校", y: "せんもんがっこう", z: "Sekolah tinggi keahlian" },
			{ x: "大学院", y: "だいがくいん", z: "Universitas S2" },
			{ x: "学校を出ます", y: "がっこうをでます", z: "Tamat sekolah" },
			{ x: "就職します", y: "しゅうしょくします", z: "Mendapat pekerjaan" },
			{ x: "結婚します", y: "けっこんします", z: "Menikah" },
			{ x: "離婚します", y: "りこんします", z: "Bercerai" },
			{ x: "再婚します", y: "さいこんします", z: "Menikah lagi" },
			{ x: "仕事やめます", y: "しごとやめます", z: "Berhenti bekerja" },
			{ x: "死にます", y: "しにます", z: "Meninggal" }
		]
	}
];