const obj = [
  {x: "食料品", y: "しょくりょうひん", z: "makanan"},
  {x: "飲料品", y: "いんりょうひん", z: "minuman"},
  {x: "工場", y: "こうじょう", z: "pabrik"},
  {x: "製造", y: "せいぞう", z: "manufaktur"},
  {x: "飲食料品製造業", y: "いんしょくりょうひんせいぞうぎょう", z: "industri pengolahan makanan dan minuman"},
  {x: "製造業", y: "せいぞうぎょう", z: "industri pengolahan"},
  {x: "農林水産省", y: "のうりんすいさんしょう", z: "Kementerian Pertanian, Kehutanan dan Perikanan"},
  {x: "国内生産額", y: "こくないせいさんがく", z: "jumlah produk dalam negeri"},
  {x: "特定技能", y: "とくていぎのう", z: "keterampilan khusus"},
  {x: "畜産食料品製造業", y: "ちくさんしょくりょうひんせいぞうぎょう", z: "industri pengolahan produk hasil peternakan"},
  {x: "水産食料品製造業", y: "すいさんしょくりょうひんせいぞうぎょう", z: "industri pengolahan makanan olahan laut"},
  {x: "調味料製造業", y: "ちょうみりょうせいぞうぎょう", z: "industri pengolahan bahan penyedap"},
  {x: "菓子製造業", y: "かしせいぞうぎょう", z: "industri pengolahan cemilan"},
  {x: "冷凍調理食品製造業", y: "れいとうちょうみりょうしょくひんせいぞうぎょう", z: "industri manufaktur masakan beku"},
  {x: "清涼飲料製造業", y: "せいりょういんりょうせいぞうぎょう", z: "industri manufaktur minuman ringan"},
  {x: "食品衛生", y: "しょくひんえいせい", z: "keamanan pangan"},
  {x: "労働安全", y: "ろうどうあんぜん", z: "keselamatan kerja"},
  {x: "衛生管理", y: "えいせいかんり", z: "manajemen keamanan"},
  {x: "知識", y: "ちしき", z: "pengetahuan"},
  {x: "信用", y: "しんよう", z: "kredibilitas"},
  {x: "作業者", y: "さぎょうしゃ", z: "pekerja"},
  {x: "作業場", y: "さぎょうじょう", z: "tempat kerja"},
  {x: "作業手順書", y: "さぎょうてじゅんしょ", z: "buku prosedur kerja"},
  {x: "保護具", y: "ほごぐ", z: "alat keselamatan"},
  {x: "機会", y: "きかい", z: "mesin"},
  {x: "器具", y: "きぐ", z: "peralatan"},
  {x: "健康", y: "けんこう", z: "kesehatan"},
  {x: "惣菜", y: "そうざい", z: "lauk-pauk"},
  {x: "在留資格者", y: "ざいりゅうしかくしゃ", z: "orang berstatus penduduk"},
  {x: "ハムソーセージ", y: "ハムソーセージ", z: "sosis daging"},
  {x: "守る", y: "まもる", z: "melindungi"},
  {x: "命", y: "いのち", z: "kehidupan"},
  {x: "施設", y: "しせつ", z: "gedung"},
  {x: "生命", y: "せいめい", z: "kehidupan"},
  {x: "食品衛生", y: "しょくひんえいせい", z: "keamanan pangan"},
  {x: "ケガ", y: "ケガ", z: "terluka"},
  {x: "基本的な", y: "きほんてきな", z: "dasar-dasar"},
  {x: "行動", y: "こうどう", z: "tindakan"},
  {x: "清潔", y: "せいけつ", z: "kebersihan"},
  {x: "設備", y: "せつび", z: "fasilitas"},
  {x: "温度", y: "おんど", z: "suhu"},
  {x: "保管", y: "ほかん", z: "penyimpanan"},
  {x: "一般衛生管理", y: "いっぱんえいせいかんり", z: "manajemen kebersihan secara umum"},
  {x: "おこなう", y: "おこなう", z: "melakukan"},
  {x: "種類", y: "しゅるい", z: "macam/jenis"},
  {x: "危害要因分析重要管理点", y: "きがいよういんぶんせきじゅうようかんりてん", z: "Hazard Analysis and Critical Control Point"},
  {x: "危害要因", y: "きがいよういん", z: "Faktor bahaya"},
  {x: "重要管理点", y: "じゅうようかんりてん", z: "Titik kontrol poin (CCP)"},
  {x: "物理的危害要因", y: "ぶつりてききがいよういん", z: "bahaya fisik"},
  {x: "化学的危害要因", y: "かがくてききがいよういん", z: "bahaya kimia"},
  {x: "生物的危害要因", y: "せいぶつてききがいよういん", z: "bahaya biologis"},
  {x: "硬い", y: "かたい", z: "keras"},
  {x: "歯が欠ける", y: "はがかける", z: "gigi terkelupas"},
  {x: "尖って", y: "とがって", z: "Lancip"},
  {x: "傷", y: "きず", z: "menggores/tergores"},
  {x: "代表的な", y: "だいひょうてき", z: "perwakilan"},
  {x: "金属片", y: "きんぞくへん", z: "serpihan logam"},
  {x: "ガラス片", y: "ガラスへん", z: "sepotong kaca"},
  {x: "プラスチック片", y: "プラスチックへん", z: "potongan plastik"},
  {x: "原因", y: "げんいん", z: "penyebab"},
  {x: "取り除く", y: "とりのぞく", z: "membuang/menghilangkan"},
  {x: "異物", y: "いぶつ", z: "benda asing"},
  {x: "卵の殻", y: "たまごのから", z: "kulit telur"},
  {x: "硬質異物", y: "こうしついぶつ", z: "benda asing yang keras"},
  {x: "混入", y: "こんにゅう", z: "kontaminasi"},
  {x: "防止", y: "ぼうし", z: "pencegahan"},
  {x: "土", y: "つち", z: "tanah"},
  {x: "小石", y: "こいし", z: "kerikil"},
  {x: "洗浄", y: "せんじょう", z: "Pencucian"},
  {x: "選別", y: "せんべつ", z: "penyortiran"},
  {x: "下処理", y: "したしょり", z: "persiapan"},
  {x: "野菜の根の部分", y: "やさいのねのぶぶん", z: "bagian akar sayuran"},
  {x: "貝の殻", y: "かいのから", z: "kerang laut"},
  {x: "魚のエラ", y: "さかなのえら", z: "insang ikan"},
  {x: "骨", y: "ほね", z: "tulang"},
  {x: "蓋", y: "ふた", z: "tutup"},
  {x: "紙片", y: "しへん", z: "selembar kertas"},
  {x: "不潔", y: "ふけつ", z: "kekotoran"},
  {x: "不衛生", y: "ふえいせい", z: "tidak sehat"},
  {x: "苦情（クレーム）", y: "くじょう", z: "keluhan (klaim)"},
  {x: "返品", y: "へんぴん", z: "kembali"},
  {x: "会社の信用", y: "かいしゃのしんよう", z: "kepercayaan perusahaan"},
  {x: "落とす", y: "おとす", z: "menjatuhkan"},
  {x: "物質", y: "ぶっしつ", z: "bahan"},
  {x: "ヒスタミン", y: "ヒスタミン", z: "histamin"},
  {x: "じゃがいもの芽", y: "じゃがいものめ", z: "kecambah kentang"},
  {x: "ソラニン", y: "ソラニン", z: "solanin"},
  {x: "アルレギー物質", y: "アルレギーぶっしつ", z: "bahan alergen"},
  {x: "殺菌剤", y: "さっきんざい", z: "fungisida"},
  {x: "薬剤", y: "やくざい", z: "obat"},
  {x: "化学物質", y: "かがくぶっしつ", z: "bahan kimia"},
  {x: "反応", y: "はんのう", z: "reaksi"},
  {x: "過剰", y: "かじょう", z: "kelebihan"},
  {x: "症状", y: "しょうじょう", z: "gejala"},
  {x: "かゆみ", y: "かゆみ", z: "gatal"},
  {x: "法律", y: "ほうりつ", z: "hukum"},
  {x: "発症数", y: "はっしょうすう", z: "jumlah kasus"},
  {x: "加工食品", y: "かこうしょくひん", z: "makanan olahan"},
  {x: "表示", y: "ひょうじ", z: "menampilkan"},
  {x: "義務", y: "ぎむ", z: "wajib"},
  {x: "推奨", y: "すいしょう", z: "rekomendasi"},
  {x: "準ずるもの", y: "じゅんずるもの", z: "setara"},
  {x: "含む", y: "ふくむ", z: "termasuk"},
  {x: "まな板", y: "まないた", z: "talenan"},
  {x: "包丁", y: "ほうちょう", z: "pisau"},
  {x: "区別", y: "くべつ", z: "masing-masing"},
  {x: "ゆで卵", y: "ゆでたまご", z: "telur rebus"},
  {x: "防ぐ", y: "ふせぐ", z: "mencegah"},
  {x: "洗浄剤", y: "せんじょうざい", z: "sabun cuci"},
  {x: "殺菌剤", y: "さっきんざい", z: "sabun sterilisasi"},
  {x: "残らない", y: "のこらない", z: "tidak tersisa"},
  {x: "流す", y: "ながす", z: "mengalir"},
  {x: "獲った", y: "とった", z: "tertangkap"},
  {x: "条件", y: "じょうけん", z: "kondisi"},
  {x: "冷蔵", y: "れいぞう", z: "pendingin"},
  {x: "冷凍", y: "れいとう", z: "pembeku"},
  {x: "保存された", y: "ほぞんされた", z: "disimpan"},
  {x: "マグロ", y: "マグロ", z: "tuna"},
  {x: "イワシ", y: "イワシ", z: "sarden"},
  {x: "サバ", y: "サバ", z: "ikan kembung"},
  {x: "赤身魚", y: "あかみざかな", z: "ikan merah"},
  {x: "似た", y: "にた", z: "sama"},
  {x: "増える", y: "ふえる", z: "meningkat"},
  {x: "じゃがいもの芽", y: "じゃがいものめ", z: "kecambah/tunas kentang"},
  {x: "吐き気", y: "はきけ", z: "mual"},
  {x: "おう吐", y: "おうと", z: "muntah"},
  {x: "下痢", y: "げり", z: "diare"},
  {x: "激しい下痢", y: "はげしいげり", z: "diare berat"},
  {x: "腹痛", y: "ふくつう", z: "sakit perut"},
  {x: "頭痛", y: "ずつう", z: "sakit kepala"},
  {x: "発熱", y: "はつねつ", z: "demam"},
  {x: "血便", y: "けつべん", z: "berak berdarah"},
  {x: "呼吸困難", y: "こきゅうこんなん", z: "sulit bernafas"},
  {x: "食中毒", y: "しょくちゅうどく", z: "keracunan makanan"},
  {x: "皮", y: "かわ", z: "kulit"},
  {x: "細菌", y: "さいきん", z: "bakteri"},
  {x: "病原", y: "びょうげん", z: "Patogen (organisme penyebab penyakit)"},
  {x: "顕微鏡", y: "けんびきょう", z: "mikroskop"},
  {x: "生き物", y: "いきもの", z: "makhluk hidup"},
  {x: "発症する", y: "はっしょうする", z: "mengembangkan gejala"},
  {x: "腸管出血性大腸菌", y: "ちょうかんしゅっけつせいだいちょうきん", z: "bakteri ecoli"},
  {x: "属菌", y: "ぞくきん", z: "bakteri"},
  {x: "サルモネラ", y: "サルモネラ", z: "Bakteri Salmonela"},
  {x: "カンピロバクター", y: "カンピロバクター", z: "Bakteri Kanpiro"},
  {x: "腸炎ビブリオ", y: "ちょうえんビブリオ", z: "Couen Biburio"},
  {x: "毒素型食中毒", y: "どくそがたしょくちゅうどく", z: "Keracunan Makanan karena Racun"},
  {x: "ノロウイルス", y: "ノロウイルス", z: "Noro Virus"},
  {x: "病原性微生物", y: "びょうげんせいびせいぶつ", z: "patogen mikroorganisme"},
  {x: "鶏卵", y: "けいらん", z: "telur ayam"},
  {x: "魚介類", y: "ぎょかいるい", z: "makanan laut"},
  {x: "激しい下痢", y: "はげしいげり", z: "diare parah"},
  {x: "毒素", y: "どくそ", z: "toksin/racun"},
  {x: "井戸水", y: "いどみず", z: "air sumur"},
  {x: "皮膚", y: "ひふ", z: "kulit"},
  {x: "芽胞", y: "がほう", z: "spora"},
  {x: "責任者", y: "せきにんしゃ", z: "penanggung jawab"},
  {x: "発生", y: "はっせい", z: "kejadian"},
  {x: "つけない", y: "つけない", z: "jangan memakainya"},
  {x: "増やさない", y: "ふやさない", z: "jangan menambah"},
  {x: "やっつける（ころす）", y: "やっつける（ころす）", z: "kekalahan (membunuh)"},
  {x: "水分", y: "すいぶん", z: "kelembaban"},
  {x: "栄養", y: "えいよう", z: "nutrisi"},
  {x: "湿度", y: "しつど", z: "kelembaban"},
  {x: "環境", y: "かんきょう", z: "lingkungan"},
  {x: "好み", y: "このみ", z: "menyukai"},
  {x: "加熱", y: "かねつ", z: "pemanasan"},
  {x: "高音", y: "こうおん", z: "suhu tinggi"},
  {x: "低音", y: "ていおん", z: "suhu rendah"},
  {x: "厳しい", y: "きびしい", z: "ketat"},
  {x: "濃度の薬剤", y: "のうどのやくざい", z: "obat konsentrasi"},
  {x: "食品全体", y: "しょくひんぜんたい", z: "semua makanan"},
  {x: "冷やす", y: "ひやす", z: "dingin"},
  {x: "代表的", y: "だいひょうてき", z: "perwakilan"},
  {x: "牡蠣", y: "かき", z: "tiram"},
  {x: "汚染", y: "おせん", z: "polusi"},
  {x: "大便", y: "だいべん", z: "kotoran"},
  {x: "吐く", y: "はく", z: "muntah"},
  {x: "次亜塩素酸ナトリウム", y: "じあえんそさん", z: "Natrium hipoklorit"},
  {x: "溶液", y: "ようえき", z: "larutan"},
  {x: "布巾", y: "ふきん", z: "kain untuk pencuci piring"},
  {x: "原則", y: "げんそく", z: "prinsip"},
  {x: "対策", y: "たいさく", z: "tindakan"},
  {x: "有効", y: "ゆうこう", z: "efektif"},
  {x: "予防", y: "よぼう", z: "pencegahan"},
  {x: "感染", y: "かんせん", z: "infeksi"},
  {x: "消毒", y: "しょうどく", z: "desinfeksi"},
  {x: "おう吐物", y: "おうとぶつ", z: "muntah"},
  {x: "専門用具", y: "せんもんようぐ", z: "alat khusus"},
  {x: "処理する", y: "しょりする", z: "proses"},
  {x: "広げない", y: "ひろげない", z: "jangan menyebar"},
  {x: "増殖", y: "ぞうしょく", z: "berkembang biak"},
  {x: "胞子", y: "ほうし", z: "spora"},
  {x: "存在", y: "そんざい", z: "adanya"},
  {x: "完全", y: "かんぜん", z: "Sempurna"},
  {x: "豆", y: "まめ", z: "kacang polong"},
  {x: "穀類", y: "こくるい", z: "biji-bijian"},
  {x: "生えた", y: "はえた", z: "berkembang"},
  {x: "寄生虫", y: "きせいちゅう", z: "parasit"},
  {x: "表面", y: "ひょうめん", z: "permukaan"},
  {x: "体内", y: "たいない", z: "di dalam tubuh"},
  {x: "生", y: "なま", z: "mentah"},
  {x: "共通", y: "きょうつう", z: "umum"},
  {x: "整 理", y: "せいり", z: "meringkas"},
  {x: "整頓", y: "せいとん", z: "merapikan"},
  {x: "清掃", y: "せいそう", z: "pembersihan"},
  {x: "清潔", y: "せいけつ", z: "merawat"},
  {x: "習慣付", y: "しゅうかんづけ", z: "membiasakan"},
  {x: "順序", y: "じゅんじょ", z: "urutan"},
  {x: "数量", y: "すうりょう", z: "kuantitas / jumlah"},
  {x: "磨く", y: "みがく", z: "menggosok"},
  {x: "拭いたり", y: "ふいたり", z: "mengelap"},
  {x: "実行", y: "じっこう", z: "eksekusi"},
  {x: "保つ", y: "たもつ", z: "menjaga"},
  {x: "役立ちます", y: "やくだちます", z: "bermanfaat"},
  {x: "触れる", y: "ふれる", z: "menyentuh"},
  {x: "交差汚染", y: "こうさおせん", z: "kontaminasi silang"},
  {x: "使い分け", y: "つかいわけ", z: "Penggunaan yang tepat"},
  {x: "通常", y: "つうじょう", z: "biasanya"},
  {x: "清潔作業区域", y: "せいけつさぎょうくいき", z: "area kerja yang bersih"},
  {x: "準清潔作業区域", y: "じゅんせいけつさぎょうくいき", z: "Area kerja semi-bersih"},
  {x: "汚染作業区域", y: "おせんさぎょうくいき", z: "area kerja yang terkontaminasi"},
  {x: "ゾーニング", y: "ゾーニング", z: "zonasi"},
  {x: "区分衛生管理", y: "くぶんえいせいかんり", z: "manajemen kebersihan terpisah"},
  {x: "取り扱い", y: "とりあつかい", z: "penanganan"},
  {x: "出荷", y: "しゅっか", z: "pengiriman"},
  {x: "通らない", y: "とおらない", z: "tidak melewati"},
  {x: "ほこり", y: "ほこり", z: "debu"},
  {x: "不要", y: "ふよう", z: "Tidak perlu"},
  {x: "状況", y: "じょうきょう", z: "situasi"},
  {x: "排水溝", y: "はいすいこう", z: "saluran pembuangan air"},
  {x: "ミキサー", y: "ミキサー", z: "mixer"},
  {x: "スライサー", y: "スライサー", z: "alat pengiris"},
  {x: "分解", y: "ぶんかい", z: "membongkar"},
  {x: "乾燥する", y: "かんそうする", z: "pengeringan"},
  {x: "たわし", y: "たわし", z: "penggosok"},
  {x: "保管庫", y: "ほかんこ", z: "gudang"},
  {x: "名称", y: "めいしょう", z: "nama"},
  {x: "検便", y: "けんべん", z: "tes tinja"},
  {x: "健康診断", y: "けんこうしんだん", z: "mcu"},
  {x: "更衣室", y: "こういしつ", z: "ruang ganti"},
  {x: "つけ爪", y: "つけつめ", z: "kuku palsu"},
  {x: "イヤリング", y: "イヤリング", z: "anting-anting"},
  {x: "ネックレス", y: "ネックレス", z: "kalung"},
  {x: "ピアス", y: "ピアス", z: "anting-anting"},
  {x: "鏡", y: "かがみ", z: "cermin"},
  {x: "衣服", y: "いふく", z: "pakaian"},
  {x: "帽子", y: "ぼうし", z: "topi"},
  {x: "粘着ローラ", y: "ねんちゃく", z: "rol perekat"},
  {x: "エアーシャワー", y: "エアーシャワー", z: "pancuran udara"},
  {x: "履き物", y: "はきもの", z: "alas kaki"},
  {x: "履き替える", y: "はきかえる", z: "ganti sepatu"},
  {x: "絞り", y: "しぼり", z: "bukaan"},
  {x: "端", y: "はし", z: "akhir"},
  {x: "襟", y: "えり", z: "kerah"},
  {x: "付着", y: "ふちゃく", z: "adhesi (keadaan melekat pada benda lain)"},
  {x: "縦襟", y: "たてえり", z: "kerah vertikal"},
  {x: "エプロン", y: "エプロン", z: "celemek"},
  {x: "腕カバー", y: "うでカバー", z: "penutup lengan"},
  {x: "ふかく", y: "ふかく", z: "dalam kombinasi"},
  {x: "合ってる", y: "あってる", z: "cocok"},
  {x: "袖", y: "そで", z: "lengan baju"},
  {x: "盛り付け", y: "もりつけ", z: "pengaturan"},
  {x: "流水", y: "りゅうすい", z: "air mengalir"},
  {x: "せっけん", y: "せっけん", z: "sabun mandi"},
  {x: "指の先", y: "ゆびのさき", z: "ujung jari"},
  {x: "秒間程", y: "びょうかんていど", z: "sekitar detik"},
  {x: "吹付", y: "ふきつけ", z: "penyemprotan"},
  {x: "交換", y: "こうかん", z: "menukarkan / mengganti"},
  {x: "徹底", y: "てってい", z: "ketelitian"},
  {x: "殺菌済み", y: "さっきんずみ", z: "disterilkan"},
  {x: "たんやつば", y: "たんやつば", z: "meludah"},
  {x: "関係", y: "かんけい", z: "hubungan"},
  {x: "品質", y: "ひんしつ", z: "kualitas"},
  {x: "影響", y: "えいきょう", z: "pengaruh"},
  {x: "香水", y: "こうすい", z: "parfum"},
  {x: "意図的", y: "いとてき", z: "disengaja"},
  {x: "記録", y: "きろく", z: "catatan"},
  {x: "倉庫", y: "そうこ", z: "gudang"},
  {x: "外部", y: "がいぶ", z: "luar"},
  {x: "照らし合わせて", y: "てらしあわせて", z: "dibandingkan"},
  {x: "届く", y: "とどく", z: "sampai"},
  {x: "受入検査", y: "うけいれけんさ", z: "Inspeksi / pengecekan penerimaan"},
  {x: "期限", y: "きげん", z: "tenggang waktu"},
  {x: "包装", y: "ほうそう", z: "pengemasan/pengepakan"},
  {x: "消費期限", y: "しょうひきげん", z: "tanggal habis tempo"},
  {x: "返品", y: "へんぴん", z: "pengembalian"},
  {x: "液状油脂", y: "えきじょうゆし", z: "minyak cair"},
  {x: "固形油脂", y: "こけいゆし", z: "minyak padat"},
  {x: "殻付き卵", y: "からつきたまご", z: "telur dengan cangkang"},
  {x: "液卵", y: "えきらん", z: "telur cair"},
  {x: "生鮮果実", y: "せいさんかじつ", z: "buah segar"},
  {x: "濃縮乳", y: "のうしょくにゅう", z: "susu pekat"},
  {x: "脱脂乳", y: "だっしにゅう", z: "susu skim"},
  {x: "練乳", y: "れんにゅう", z: "susu kental"},
  {x: "容器", y: "ようき", z: "wadah"},
  {x: "冷蔵庫", y: "れいぞうこ", z: "lemari pendingin"},
  {x: "冷凍庫", y: "れいとうこ", z: "lemari pembeku"},
  {x: "隙間", y: "すきま", z: "celah"},
  {x: "詰め込んで", y: "つめこんで", z: "Penuh sesak"},
  {x: "全体", y: "ぜんたい", z: "seluruh"},
  {x: "割詰めた", y: "わりつめた", z: "dialokasikan"},
  {x: "互いに", y: "たがいに", z: "satu sama lain"},
  {x: "節電", y: "せつでん", z: "penghematan energi"},
  {x: "測定", y: "そくてい", z: "pengukuran"},
  {x: "結果", y: "けっか", z: "hasil"},
  {x: "食品衛生法", y: "しょくひんえいせいほう", z: "UU Sanitasi Pangan"},
  {x: "使用期限", y: "しようきげん", z: "tanggal penggunaan"},
  {x: "賞味期限", y: "しょうみきげん", z: "tanggal terbaik sebelum"},
  {x: "消費期限", y: "しょうひきげん", z: "tanggal kadaluarsa"},
  {x: "企業", y: "きぎょう", z: "perusahaan"},
  {x: "未開封", y: "みかいふう", z: "Belum dibuka"},
  {x: "納品された", y: "のうひんされた", z: "terkirim"},
  {x: "開封", y: "かいふう", z: "membuka"},
  {x: "解凍", y: "かいとう", z: "Pencairan"},
  {x: "加温", y: "かおん", z: "Pemanasan"},
  {x: "自然", y: "しぜん", z: "alami"},
  {x: "汁", y: "しる", z: "cairan"},
  {x: "ドリップ", y: "ドリップ", z: "menetes"},
  {x: "トレー", y: "トレー", z: "baki / nampan"},
  {x: "網目トレー", y: "あまみトレー", z: "nampan jaring"},
  {x: "穴", y: "あな", z: "lubang"},
  {x: "密閉", y: "みっぺい", z: "tertutup"},
  {x: "移し替えて", y: "うつしかえて", z: "pindahkan"},
  {x: "固形", y: "こけい", z: "padat"},
  {x: "ペースト", y: "ペースト", z: "tempel"},
  {x: "劣化", y: "れっか", z: "kemerosotan / menurun"},
  {x: "適正濃度", y: "てきせいのうど", z: "konsentrasi yang sesuai"},
  {x: "食塩水", y: "しょくえんすい", z: "larutan garam"},
  {x: "製造工程", y: "せいぞうこうてい", z: "proses produksi"},
  {x: "選別", y: "せんべつ", z: "penyortiran"},
  {x: "分別", y: "ぶんべつ", z: "penyortiran"},
  {x: "裁断", y: "さいだん", z: "pemotongan"},
  {x: "魚のウロコ", y: "さかなのウロコ", z: "sisik ikan"},
  {x: "確実", y: "かくじつ", z: "kepastian"},
  {x: "廃棄する", y: "はいきする", z: "membuang"},
  {x: "細断", y: "さいだん", z: "pencacahan"},
  {x: "混合", y: "こんごう", z: "pencampuran"},
  {x: "成型", y: "せいけい", z: "pembentukan"},
  {x: "配管", y: "はいかん", z: "perpipaan"},
  {x: "線異物検出機", y: "せん いぶつけんしゅつき", z: "detektor logam"},
  {x: "微生物", y: "びせいぶつ", z: "mikroorganisme"},
  {x: "加熱殺菌", y: "かねつさっきん", z: "sterilisasi panas"},
  {x: "消化", y: "しょうか", z: "pencernaan"},
  {x: "中心温度", y: "ちゅうしんおんど", z: "temperatur inti"},
  {x: "かたまり", y: "かたまり", z: "gumpalan"},
  {x: "確かめます", y: "たしかめます", z: "memastikan"},
  {x: "冷却", y: "れいきゃく", z: "pendinginan"},
  {x: "冷える", y: "ひえる", z: "dingin"},
  {x: "具大的", y: "ぐだいてき", z: "secara khusus"},
  {x: "損なわない", y: "そこなわない", z: "tidak merusak"},
  {x: "次亜塩素酸ナトリウム", y: "じあえんそさん", z: "natrium hipoklorit"},
  {x: "濃度", y: "のどう", z: "konsentrasi"},
  {x: "保存性", y: "ほぞんせい", z: "umur penyimpanan"},
  {x: "生鮮", y: "せいせん", z: "segar"},
  {x: "硬さ", y: "かたさ", z: "kekerasan"},
  {x: "弾力", y: "だんりょく", z: "elastisitas"},
  {x: "食感", y: "しょっかん", z: "tekstur"},
  {x: "風味", y: "ふうみ", z: "rasa"},
  {x: "短時間", y: "たんじかん", z: "waktu singkat"},
  {x: "急速", y: "きゅうそく", z: "cepat"},
  {x: "充填", y: "じゅうてん", z: "pengisian"},
  {x: "包装", y: "ほうそう", z: "pengemasan"},
  {x: "検査", y: "けんさ", z: "inspeksi / pengecekan"},
  {x: "キャップ", y: "キャップ", z: "tutup"},
  {x: "印字します", y: "いんじします", z: "mencetak"},
  {x: "ミス", y: "ミス", z: "kesalahan"},
  {x: "空気", y: "くうき", z: "udara"},
  {x: "中身", y: "なかみ", z: "isi"},
  {x: "正常", y: "せいじょう", z: "normal"},
  {x: "テストピース", y: "テストピース", z: "Benda uji"},
  {x: "機能", y: "きのう", z: "fungsi"},
  {x: "時点", y: "じてん", z: "titik waktu"},
  {x: "形状不良品", y: "けいじょうふりょうひん", z: "Bentuk produk cacat"},
  {x: "項目", y: "こうもく", z: "barang"},
  {x: "法律", y: "ほうりつ", z: "hukum"},
  {x: "食品製造業者", y: "しょくひんせいぞうぎょうしゃ", z: "produsen makanan"},
  {x: "自主的", y: "じしゅてき", z: "Sukarela"},
  {x: "配送", y: "はいそう", z: "pengiriman"},
  {x: "サンプル", y: "サンプル", z: "Sampel"},
  {x: "クレーム", y: "クレーム", z: "klaim"},
  {x: "一般生菌数", y: "いっぱんせいきんすう", z: "Jumlah bakteri hidup secara umum"},
  {x: "一般的に", y: "いっぱんてきに", z: "khas"},
  {x: "大腸菌", y: "だいちょうきん", z: "Escherichia coli"},
  {x: "大腸菌群", y: "だいちょうきんぐん", z: "Bakteri koliform"},
  {x: "一定の割合", y: "いっていのわりあい", z: "persentase tertentu"},
  {x: "抜き出す", y: "ぬきだす", z: "mengeluarkan"},
  {x: "仕組み", y: "しくみ", z: "struktur"},
  {x: "監視", y: "かんし", z: "pengawasan"},
  {x: "従って", y: "したがって", z: "sesuai"},
  {x: "運用される", y: "うんようされる", z: "dioperasikan"},
  {x: "判断", y: "はんだん", z: "pertimbangan"},
  {x: "逸脱", y: "いつだつ", z: "menyimpang"},
  {x: "検証方法", y: "けんしょうほうほう", z: "metode verifikasi"},
  {x: "除去", y: "じょきょ", z: "menghilangkan"},
  {x: "低減", y: "ていげん", z: "mengurangi"},
  {x: "有効", y: "ゆうこう", z: "efektif"},
  {x: "管理基準", y: "かんりきじゅん", z: "standar manajemen"},
  {x: "代表的", y: "だいひょうてき", z: "umum"},
  {x: "参照", y: "さんしょう", z: "referensi"},
  {x: "改善措置", y: "かいぜんそち", z: "langkah-langkah perbaikan"},
  {x: "加熱ゾーン", y: "かねつゾーン", z: "zona pemanasan"},
  {x: "速度", y: "そくど", z: "kecepatan"},
  {x: "調整", y: "ちょうせい", z: "pengaturan"},
  {x: "不足", y: "ぶそく", z: "kekurangan"},
  {x: "廃棄する", y: "はいきする", z: "membuang"},
  {x: "実施した", y: "じっしした", z: "dilakukan"},
  {x: "管理手段", y: "かんりしゅだん", z: "langkah-langkah pengelolaan"},
  {x: "殺菌液の濃度", y: "さっきんえきののうど", z: "konsentrasi larutan sterilisasi"},
  {x: "計る", y: "はかる", z: "ukuran"},
  {x: "事実", y: "じじつ", z: "fakta"},
  {x: "修正する", y: "しゅうせいする", z: "memperbaiki"},
  {x: "労働災害", y: "ろうどうさいがい", z: "kecelakaan industri"},
  {x: "経験", y: "けいけん", z: "pengalaman"},
  {x: "未熟練作業者", y: "みじゅくれんさぎょうしゃ", z: "pekerja tidak terampil"},
  {x: "未満", y: "みまん", z: "kurang dari"},
  {x: "占める", y: "しめる", z: "menempati"},
  {x: "割合", y: "わりあい", z: "setengah"},
  {x: "一般社団法人日本労働安全衛生コンサルタント協会", y: "いっぱんしゃだほうじんいほんろどうあんぜねいせいコンサルタントきょうかい", z: "Japan Association of Safety and Health Consultants"},
  {x: "製造業向け未熟練労働者に対する安全衛生教育マニュアル", y: "せいぞうぎょうむけみじゅくんれんろうどうしゃにたいするあんぜんえいせいきょういくマニュアル", z: "Manual Pendidikan Keselamatan dan Kesehatan untuk Pekerja Tidak Terampil di Industri Manufaktur"},
  {x: "災害", y: "さいがい", z: "kecelakaan"},
  {x: "慣れてない", y: "なれてない", z: "belum terbiasa"},
  {x: "気が付いてない", y: "きがついてない", z: "tidak menyadarinya"},
  {x: "多いじゅん", y: "おおいじゅん", z: "kebanyakan"},
  {x: "転倒", y: "てんとう", z: "terpeleset/tersandung"},
  {x: "はさまれ", y: "terjepit", z: "terjepit"},
  {x: "巻き込まれ", y: "まきこまれ", z: "terjerat"},
  {x: "切れる", y: "きれる", z: "terpotong"},
  {x: "擦れ", y: "こすれ", z: "teriris"},
  {x: "主な", y: "おもな", z: "utama"},
  {x: "つまずいたり", y: "つまずいたり", z: "tersandung atau tersandung"},
  {x: "墜落", y: "ついらく", z: "menggelinding"},
  {x: "打った", y: "うった", z: "patah"},
  {x: "つぶれた", y: "つぶれた", z: "patah"},
  {x: "さまって", y: "さまって", z: "tersangkut"},
  {x: "つまった", y: "つまった", z: "tersumbat"},
  {x: "捻挫します", y: "ねんざします", z: "terkilir"},
  {x: "やけど", y: "terbakar", z: "terbakar"},
  {x: "全身", y: "ぜんしん", z: "seluruh tubuh"},
  {x: "腰痛", y: "ようつう", z: "sakit pinggang"},
  {x: "繰り返す", y: "くりかえす", z: "berulang kali"},
  {x: "熱中症", y: "ねっちゅうしょう", z: "sengatan panas"},
  {x: "体内の水分", y: "たいないのすいぶん", z: "keseimbangan air"},
  {x: "塩分のバランス", y: "えんぶんのバランス", z: "keseimbangan garam"},
  {x: "体温", y: "たいおん", z: "suhu tubuh"},
  {x: "崩れる", y: "くずれる", z: "terganggu"},
  {x: "激突", y: "げきとつ", z: "benturan"},
  {x: "移動中", y: "いどうちゅう", z: "sedang bergerak"},
  {x: "目標", y: "もくひょう", z: "tujuan"},
  {x: "活動", y: "かつどう", z: "kegiatan/aktifitas"},
  {x: "順書", y: "じゅんしょ", z: "prosedur"},
  {x: "保ちます", y: "たもちます", z: "menjaga"},
  {x: "道具", y: "どうぐ", z: "peralatan"},
  {x: "動線", y: "どうせん", z: "aliran kerja"},
  {x: "枠", y: "わく", z: "bingkai"},
  {x: "故障", y: "こしょう", z: "rusak/kerusakan"},
  {x: "感染症", y: "かんせんしょう", z: "penyakit infeksi"},
  {x: "保護メガネ", y: "ほごめがね", z: "Kacamata pelindung"},
  {x: "耳栓", y: "みみせん", z: "Penutup telinga"},
  {x: "ゴム手袋", y: "ゴムてぶくろ", z: "Sarung tangan karet"},
  {x: "ミトン手袋", y: "ミトンてぶくろ", z: "Sarung tangan mitten"},
  {x: "耐熱エプロン", y: "たいねつアプロン", z: "Celemek tahan panas"},
  {x: "メクセル手袋", y: "メクセルてぶくろ", z: "Sarung tangan mexel"},
  {x: "安全靴", y: "あんぜんぐつ", z: "Sepatu keselamatan"},
  {x: "くさり手袋", y: "くさりてぶくろ", z: "Sarung tangan besi"},
  {x: "カバー付き長靴", y: "カバーつきながぐつ", z: "Sepatu bot dengan penutup"},
  {x: "高所場所", y: "こうしょばしょ", z: "tempat yang tinggi"},
  {x: "薬品", y: "やくひん", z: "obat"},
  {x: "微粉", y: "びふん", z: "bubuk halus"},
  {x: "高圧洗浄", y: "こうあつせんじょう", z: "pencucian bertekanan tinggi"},
  {x: "液体", y: "えきたい", z: "cairan"},
  {x: "騒音", y: "そうおん", z: "kebisingan"},
  {x: "繊維", y: "せんい", z: "serat"},
  {x: "編み", y: "あみ", z: "rajutan"},
  {x: "つま先", y: "つまさき", z: "jari kaki"},
  {x: "かかとに", y: "かかとに", z: "dengan tumit"},
  {x: "鋼板", y: "こうばん", z: "pelat baja"},
  {x: "装着", y: "そうちゃく", z: "lampiran"},
  {x: "ステンレス鋼", y: "ステンレスこう", z: "besi tahan karat"},
  {x: "耐油", y: "たいゆ", z: "tahan minyak"},
  {x: "靴底", y: "くつぞこ", z: "sol sepatu"},
  {x: "上部", y: "じょうぶ", z: "bagian atas"},
  {x: "難聴", y: "なんちょう", z: "gangguan pendengaran"},
  {x: "共同", y: "きょうどう", z: "kerja sama"},
  {x: "よそ見", y: "よそみ", z: "mengalihkan pandangan"},
  {x: "無駄話", y: "ムダはなし", z: "pembicaraan kosong"},
  {x: "横断方法", y: "おうだんほうほう", z: "metode penyeberangan"},
  {x: "指差呼称", y: "しさこしょう", z: "tunjuk dan ucap"},
  {x: "合図", y: "あいず", z: "tanda/isyarat"},
  {x: "信号", y: "しんごう", z: "sinyal"},
  {x: "標識", y: "ひょうしき", z: "tanda"},
  {x: "作業対象", y: "さぎょうたいしょう", z: "benda kerja"},
  {x: "理解する", y: "りかいする", z: "memahami"},
  {x: "補足資料", y: "ほそくしりょう", z: "materi tambahan"},
  {x: "参照", y: "さんしょう", z: "referensi"},
  {x: "落ち着いて", y: "おちついて", z: "tenang"},
  {x: "無理", y: "むり", z: "memaksakan diri"},
  {x: "始業前点検", y: "しぎょうまえてんけん", z: "inspeksi pra-operasional"},
  {x: "異常", y: "いじょう", z: "kelainan"},
  {x: "安定", y: "あんてい", z: "stabil"},
  {x: "振動", y: "しんどう", z: "getaran"},
  {x: "ボルト", y: "ボルト", z: "baut"},
  {x: "ネジ", y: "ねじ", z: "sekrup"},
  {x: "部品", y: "ぶひん", z: "suku cadang"},
  {x: "点灯", y: "てんとう", z: "dinyalakan"},
  {x: "消灯", y: "しょうとう", z: "dimatikan"},
  {x: "対応", y: "たいおう", z: "tindakan"},
  {x: "停止", y: "ていし", z: "berhenti"},
  {x: "取り除く", y: "とりのぞく", z: "mengatasi"},
  {x: "電源", y: "でんげん", z: "tombol daya"},
  {x: "非常停止ボタン", y: "ひじょうていしボタン", z: "tombol stop darurat"},
  {x: "操作盤", y: "そうさばん", z: "panel kontrol"},
  {x: "安全装置", y: "あんぜんそうち", z: "alat pengaman"},
  {x: "自動的", y: "じどうてき", z: "secara otomatis"},
  {x: "フェールセーフ", y: "フェールセーフ", z: "gagal-aman"},
  {x: "修理", y: "しゅうり", z: "memperbaiki"},
  {x: "チェーン", y: "チェーン", z: "rantai"},
  {x: "故障対応中", y: "こしょうたいおうちゅう", z: "sedang diperbaiki"},
  {x: "メンテナンス", y: "メンテナンス", z: "pemeliharaan"},
  {x: "計画", y: "けいかく", z: "rencana"},
  {x: "整備", y: "せいび", z: "pemeliharaan"},
  {x: "生産", y: "せいさん", z: "produksi"},
  {x: "塩素系の洗剤", y: "えんそけいのせんざい", z: "detergen berbahan dasar klorin"},
  {x: "酸性洗剤", y: "さんせいせんざい", z: "detergen asam"},
  {x: "有毒な塩素ガス", y: "ゆうどくなえんそガス", z: "gas klorin beracun"},
  {x: "発生", y: "はっせい", z: "menghasilkan"},
  {x: "消毒用アルコール", y: "しょうどくようアルコール", z: "Alkohol disinfektan"},
  {x: "同時に", y: "どうじに", z: "pada saat yang sama"},
  {x: "火災", y: "かさい", z: "kebakaran"},
  {x: "異常事態", y: "いじょうじたい", z: "situasi abnormal"},
  {x: "判断", y: "はんだん", z: "keputusan"},
  {x: "二次災害", y: "にじさいがい", z: "kecelakaan sekunder"},
  {x: "定期的", y: "ていきてき", z: "secara rutin"},
  {x: "日頃", y: "ひごろ", z: "setiap hari"},
  {x: "訓練", y: "くんれん", z: "pelatihan"},
  {x: "避難訓練", y: "ひなんくんれん", z: "latihan evakuasi"},
  {x: "想定した避難訓練", y: "そうていしたひなんくんれん", z: "latihan evakuasi bencana"},
  {x: "レバーがぐらぐらします", y: "レバーがぐらぐらします", z: "Tuasnya bergetar"},
  {x: "事例", y: "じれい", z: "kasus"},
  {x: "社内", y: "しゃない", z: "Di dalam perusahaan"},
  {x: "身近", y: "みじか", z: "diri sendiri"},
  {x: "社外", y: "しゃがい", z: "Di luar perusahaan"},
  {x: "ヒヤリ・ハット", y: "ヒヤリ・ハット", z: "nyaris celaka"},
  {x: "ハインリッヒの法則", y: "ハインリッヒのほうりつ", z: "hukum Heinrich"},
  {x: "体験した", y: "たいけんした", z: "mengalami"},
  {x: "危険予知訓練", y: "きけんよちくんれん", z: "Latihan Prediksi Bahaya"},
  {x: "実際", y: "じっさい", z: "sebenarnya"},
  {x: "潜在的な危険", y: "せんざいてきなきけん", z: "potensi bahaya"},
  {x: "酸欠になる", y: "さんけつになる", z: "kekurangan oksigen"},
  {x: "有害物にやられる", y: "ゆうがいぶつやられる", z: "terkena zat berbahaya"},
  {x: "状況", y: "じょうきょう", z: "situasi"},
  {x: "対策", y: "たいさく", z: "penanganan"},
  {x: "姿勢", y: "しせい", z: "sikap"},
  {x: "イラスト", y: "イラスト", z: "ilustrasi"},
  {x: "示した", y: "しめした", z: "diindikasikan"},
  {x: "警戒", y: "けいかい", z: "kewaspadaan"},
  {x: "積まれた", y: "つまれた", z: "menumpuk"},
  {x: "煮物", y: "にもの", z: "makanan rebus"},
  {x: "ガスコンロ", y: "ガスコンロ", z: "tungku gas"},
  {x: "室内", y: "しつない", z: "dalam"},
  {x: "両手", y: "りょうて", z: "kedua tangan"},
  {x: "通路", y: "つうろ", z: "lorong / jalan"},
  {x: "空箱", y: "からばこ", z: "kotak kosong"},
  {x: "つまずき", y: "つまずき", z: "tersandung"},
  {x: "転倒", y: "てんとう", z: "jatuh"},
  {x: "重ねて", y: "かさねて", z: "tumpuk"},
  {x: "数", y: "かず", z: "jumlah"},
  {x: "突然", y: "とつぜん", z: "tiba-tiba"},
  {x: "異物の除去", y: "いぶつのじょきょ", z: "mengeluarkan benda asing"},
  {x: "作業台", y: "さぎょうだい", z: "meja kerja"},
  {x: "押し板", y: "おしいた", z: "papan dorong"},
  {x: "止金具", y: "とめかなぐ", z: "pengikat / pengunci"},
  {x: "鉄板", y: "てっぱん", z: "plat besi"},
  {x: "鍋", y: "なべ", z: "panci"},
  {x: "釜", y: "かま", z: "ketel"},
  {x: "膝", y: "ひざ", z: "lutut"},
  {x: "曲げて", y: "まげて", z: "membengkokkan"},
  {x: "抱えて", y: "かかえて", z: "tahan, peluk"},
  {x: "伸ばす", y: "のばす", z: "menggeliat, memanjangkan"},
  {x: "生あん工程", y: "せいあんこうてい", z: "proses pasta kacang mentah"},
  {x: "診断", y: "しんだん", z: "diagnosa"},
  {x: "汗", y: "あせ", z: "keringat"},
  {x: "安静", y: "あんせい", z: "istirahat"},
  {x: "緩める", y: "ゆるめる", z: "melonggarkan"},
  {x: "脇の下", y: "わきのした", z: "ketiak"},
  {x: "足の付け根", y: "あしのつけね", z: "pangkal kaki"},
  {x: "スポーツドリンク", y: "スポーツドリンク", z: "minuman olahraga"},
  {x: "一時停止", y: "いちじていし", z: "berhenti sebentar"},
  {x: "運転者", y: "うんてんしゃ", z: "pengemudi"},
  {x: "立入禁止", y: "たちいりきんし", z: "dilarangan masuk"},
  {x: "走ることを禁止", y: "はしることをきんし", z: "dilarang berlari"},
  {x: "開放厳禁", y: "かいほうげんきん", z: "dilarang keras untuk dibuka"},
  {x: "手で触れることを禁止す", y: "てでふれることをきんし", z: "dilarang menyentuh dengan tangan"},
  {x: "点検中", y: "てんけんちゅう", z: "sedang diperiksa"},
  {x: "スイッチをいれるな", y: "スイッチをいれるな", z: "jangan hidupkan saklarnya"},
  {x: "手を触れるな", y: "てをふれるな", z: "Jangan sentuh"},
  {x: "はさまれ注意", y: "はさまれちゅうい", z: "Hati-hati terjepit"},
  {x: "火傷注意", y: "やけどちゅうい", z: "Hati-hati terhadap luka bakar"},
  {x: "高温注意", y: "こうおんちゅうい", z: "Hati-hati terhadap suhu tinggi"},
  {x: "足元注意", y: "あしもとちゅうい", z: "Perhatikan langkahmu"},
  {x: "危険転倒注意", y: "きけんてんとうちゅうい", z: "Bahaya terjatuh"},
  {x: "開口部注意", y: "かいこうぶちゅうい", z: "Hati-hati dengan bukaan"},
  {x: "転落注意", y: "てんらくちゅうい", z: "Hati-hati agar tidak jatuh"},
  {x: "切断注意", y: "せつだんちゅうい", z: "Hati-hati dalam memotong"},
  {x: "回転物に手をだすな", y: "かいてんものてをだすな", z: "Jangan menyentuh benda berputar"},
  {x: "感電注意", y: "かんでんちゅうい", z: "Hati-hati terhadap sengatan listrik"},
  {x: "頭上注意", y: "ずじょうちゅうい", z: "perhatikan kepalamu"},
  {x: "ゴーグル着用", y: "ゴーグルちゃくよう", z: "Mengenakan kacamata"},
  {x: "保護メガネ着用", y: "ほごめがねちゃくよう", z: "Kenakan kacamata pengaman"},
  {x: "非常口", y: "ひじょうぐち", z: "pintu darurat"},
  {x: "消火器", y: "しょうかき", z: "alat pemadam api"}
];
// abjad
// obj.sort((a, b) => a.x.localeCompare(b.x));
// kata sedikit
// obj.sort((a, b) => a.y.length - b.y.length);
// 
obj.sort((a, b) => {
  // Pertama urutkan berdasarkan panjang kata pada 'y'
  if (a.y.length !== b.y.length) {
    return a.y.length - b.y.length;
  }
  // Jika panjang kata sama, urutkan secara abjad
  return a.y.localeCompare(b.y);
});